### ISSUE TITLE
Feature Request:  JSON RPC call for the getrandom_outs.bin method using a JSON input

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#1363]
Jaxx wants a JSON RPC call for the getrandom_outs.bin method using a JSON input. 

The daemon would be choosing the outputs istead of the wallet, which has an effect on users privacy.

more comments appreciated

**Comment by AugustoL** [comment]
How will this effect users privacy?

**Comment by tewinget** [comment]
The daemon will know which output from each ring signature is the user's
because it chose the others.

This is dealt with by shifting the output selection to the client side, and
a JSON-RPC call is already written as needed for this in the upcoming zmq
rpc.

Will hasten my efforts.
On Nov 21, 2016 11:09 AM, "Augusto" <notifications@github.com> wrote:

How will this effect users privacy?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/monero-project/monero/issues/1363#issuecomment-261982595>,
or mute the thread

**Comment by AugustoL** [comment]
Thanks @tewinget we are searching for random inputs on the client side using /getblocks and /gettransactions , I was wondering If we can did it using RPC to make the built of TX faster.

So as I understand the daemon knows if any of the outputs belongs to the user, right?, what if we had a randomOutputs rpc call that just return any random output (without checking ownership of outputs)? later on the client we can check if any of that outputs belongs to the suer, if not we can make the tx or ask for random outputs again.

**Comment by tewinget** [comment]
I think you misunderstand.  Let's discuss it on IRC (#monero-dev on
freenode), as this discussion will quickly fall out of scope for this
feature request.

**Comment by NanoAkron** [comment]
Really pleased to see these conversations starting :)

**Comment by moneromooo-monero** [comment]
tewinget is correct.

Basically, if you use a daemon to ask "gimme N outputs of denomination X", then send a new tx to that daemon, and the daemon sees an input to that tx using the N outputs it sent earlier, plus another one, it can be sure that extra one is the real one.

The wallet now asks for specific outs, and, crucially, includes the one it intends to send. See the get_outs.bin call, which does that instead of the older getrandom_outs.bin.

**Comment by moneromooo-monero** [comment]
> we are searching for random inputs on the client side using /getblocks and /gettransactions

Note that outputs are referenced by index, so in order to select random outputs, you need only know the number of outputs for a given denomination, say N, then pick P random numbers in [0,N). I'm not sure if you're doing something  more complicated here, but it kinda reads like it.

You get N by calling the histogram RPC. See an example in src/wallet/wallet2.cpp, get_outs (it does something a bit more funky to try to adapt to de facto distribution, but that can be ignored for a first implementation).

**Comment by AugustoL** [comment]
@moneromooo-monero thanks for the detailed answer, let me dig again more deeply into the code to see again what we need.

**Comment by moneromooo-monero** [comment]
I added a JSON based version of get_outs.bin, called get_outs.
This is to encourage doing the right thing. There will not be a text based version of getrandom_outs.bin.

**Comment by medusadigital** [comment]
closing this for now. @AugustoL if youz have another request please open another ticket.
