### ISSUE TITLE
Feature request: add aditional 0-output in case of one output (when using RingCT)

### ISSUE THREAD

**Issue by dnaleor** [monero-project/monero#1375]
It is possible to add 0 XMR outputs using RIngCT.

I think in case someone builds a transaction that would only contain a single output, it would be beneficial for privacy to also add a 0 XMR output. This would make this transaction indistinguishable from any other transaction.

If certain transactions only have one output, this lowers the privacy significantly, as an observer will be able to know that all inputs (although using ring sig) are consolidated into one new output. When using the 0-output, it just looks like a regular "payment and change" transaction 

edit: this 0-output could be sent to a random generated address, or could be sent to the sender as "change". Avoid using an address that is already used by someone else, as this will be confusing when he refreshes his balance.

**Comment by moneromooo-monero** [comment]
This adds pointless spam to the blockchain. However, if you want this, there's a patch which does this in my ringct history, which I subsequently took out, it was in src/wallet/wallet2.cpp and just a few lines IIRC, so should be easy to restore locally.

**Comment by NanoAkron** [comment]
Is it possible for someone to construct a transaction with a single output after ringct activates?

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by dnaleor** [comment]
it does indeed at some "spam" to the blockchain, but on the other hand, it improves privacy, make (almost) all transactions look the same. The more uniformity the better. Ring sigantures also add "spam" to the blockchain because we don't know if transactions are spent or unspent. Imho it's a trade-off. 

I will look into your code.

**Comment by NanoAkron** [comment]
Is there any way to 'quantify' the relative loss of privacy? 

Maybe it would be better to inform the user their transaction is going to result in a single output which may compromise their security, and present them with the option of splitting it instead.

**Comment by kewde** [comment]
The only case where privacy loss may occur is in very odd situations. Adding a 0 output is not worth the trade-off.

This would however be prevent situations where a user or service systematically spends the whole output without any change over and over again establishing a pattern of one-output transactions only. 

Another one of them could be due to the fact that change addresses generally contain a lower amount of XMR (compared to the intended outgoing output) which would also results into it being more likely being spent along with multiple other inputs to achieve the necessary amount. If you would mix with one-output-transactions ONLY (which is highly unlikely but nonetheless a possible scenario) then it is more likely that the outputs stemming from transactions with multiple outputs are the ones being spent because the spender has scrapped all his change together. However, that is very very far fetched.

**Comment by dnaleor** [comment]
> This would however be prevent situations where a user or service systematically spends the whole output without any change over and over again establishing a pattern of one-output transactions only.

I don't want to sound paranoid, but this can lead to anonimity (and maybe even mild fungibility) issues. I'm a fan of making all transactions as uniform as possible. Maybe enforcing the 0-output is for some a bridge too far, but making it the default should be considered, imho.

**Comment by moneromooo-monero** [comment]
I'll do that when Shen or Surae or other has a good study showing the details of what this entails :)

But FYI, I have a branch somewhere with a system that will send every input of a transaction separately, with random delay between the transactions. This system is meant to avoid any temporal associations between inputs (because there's only one, ever). This system would cause a LOT of transactions with a single input *and* a single output, and these are even better than the 2x2.

There is a possibility that having just one output means you can have a special rct proof that's smaller than what you'd otherwise be, though this may involve more complex changes, so it's something I want to keep available for the future.

**Comment by dnaleor** [comment]
I like the idea of only spending one input in a transaction at a time, but this is probably not possible for payments to businesses. It's a cool idea though, makes it indeed a lot more private, but adoption of this will be hard:

*Businesses want to see at least an unconfirmed transaction, if they only see a partial unconfirmed transaction, they can't even be sure that in the next x minutes the other parts will be send. This is a weak argument as I don't believe in using crypto for transactions in retail stores. It does however complicates how businesses integrate with monero online as well. 
*It's a mess when something goes wrong in the middle of broadcasting the stream of payments. Again, nothing that can't be solved, but needs additional tools and code for payment processors
*What about payment ID's ? When sending a payment that has a paymentID attached, will this paymentID be attached to all partial transactions? Or can we think about a scheme that changes the PaymentID with every partial transaction but still somehow links them together (and only the sender and receiver can do this) ? 

Also, as you already said yourself, you will have at least one transaction with a change output in this "stream payment". 
So I do expect that, even if the "payment stream" system gets implemented, it'll take a whole before it'll become popular. So a lot of transactions will still have 2 outputs. Therefore, the stream payments will stand out among the "normal" payments. So I would still advocate for making payments look uniform and having that 0-output (at least as an option, preferable on by default). 

Another possibility for this is to have your wallet consolidate 2 outputs into one bigger one at random time intervals (and have that 0-output to not make this visible). If you do this, you end up with one big (or a few big) txo's that you can then spend separately (or use a maximum of 2 in a spending transaction). Although this is weaker than spending the individual outputs separately.

**Comment by kewde** [comment]
There might be another reason for why you would one to include a 0 output into your commitment.

Quoting section 3.2 of the [RingCT paper](https://lab.getmonero.org/pubs/MRL-0005.pdf)
> Note that z is not computable to the originator of Xc’s coins, unless they know both of the y1;y2, but even this can be simply mitigated by including an additional change address (the usual case is
that the second commitment, with y2 as mask, is sent to yourself as change).

If you spend a ring signature back to the originator of Xc in one single output then they are able to calculate z.

**Comment by dnaleor** [comment]
yeah kwede, you're right. If inputs are spend separately (one input, one output) then the sender will be able to "follow" a certain txo of which he knows what the amount is (ingoring the fact that ring sigs are being used). When that 0-out is added, there is uncertainty about what the amount of the 2 new txo's is.

**Comment by kewde** [comment]
He would still need to have knowledge of the mask  of the single output y1, limiting the attack.

**Comment by moneromooo-monero** [comment]
Feel free to ping me or others in -dev for such things, I found this by chance.
I did not realize that having one output would cause this. I patched this now.

**Comment by NanoAkron** [comment]
Hi @dnaleor Has version 0.10.1 achieved what you imagined with this? If so, would you mind closing this issue?

**Comment by luigi1111** [comment]
Solved in #1415

**Comment by kewde** [comment]
I wanted to add a bit of information to this thread, as it seems like a good place to store this.

"I the a 0 input required for _mathematical_ reasons?"
Yes.

Let's envision the scenario of A->B->A,  where A can freely chose the public key on which B receives the coins. This is an important fact, because the re-usage of a public key can be detrimental. 

The formula for keyimages is as follows: 
= `(x) * HashToEc(P) `
where x is the private key, and P the corresponding public key.

In the case of A->B->A, the adversary A can compute z (see above).
He still can't sign for the ring signature, so the funds are okay. But re-usage of a public keys allows you to do some funky stuff. 

pre-RCT
-------------
TX1, with keyImage_1
= `(b) * HashToEc(B) `
where b is Bobs private key, and B the corresponding public key.

post-RCT with public key re-usage of pre-RCT
-------------
TX1, with keyImage_1
= `(b + z) * HashToEc(B) `
where b is Bobs private key, and B the corresponding public key.

This can be transformed to:
= `(b) * HashToEc(B)  + z * HashToEc(B) `
= `keyImage_1  + z * HashToEc(B) `
Alice is able to solve for the key image and all anonymity is mathematically lost, she knows both keyImage_1 (by eliminating the need for the knowledge of private key b) and has knowledge of z (as stated above) and knows B.

The keyimage is unique, it is not the same one as pre-RCT.
