### ISSUE TITLE
DB sync modes

### ISSUE THREAD

**Issue by luigi1111** [monero-project/monero#1463]
safe/fast when why how etc.

(Continues #706 )

**Comment by iamsmooth** [comment]
It was pointed out that it is hard to tell when the DB is synced in order to switch to safe mode.

I don't think this is a huge issue because we probably don't ever want to use unsafe modes after the first sync. If you have previously synced and have a non-corrupt DB stored locally, you probably don't want to corrupt it (and need a full resync to recover) by having a catch-up sync fail (people who really do want this can use some advanced setting).

So I'd suggest something like using a fast/unsafe mode on first open when creating a new DB. After that always use a safe mode. (Again, advanced settings are possible for people who know what they are doing and want them.)

**Comment by NanoAkron** [comment]
@hyc, what do you think?

**Comment by hyc** [comment]
Sounds OK to me. I'll think about how to patch that in.

**Comment by iamsmooth** [comment]
> We still want to know sync has finished, for a daemon that's been left running.

Yes I thought about that at first and didn't come up with anything great. Maybe switch unconditionally after 24 hours? Switch on the first occurrence of elapsed time between new blocks added to the DB >2 minutes?

**Comment by moneromooo-monero** [comment]
I'd say when a block is added to the database, that's not from a sync call. This means the blockchain's top block at the time was the same as what miners were mining on.

**Comment by iamsmooth** [comment]
Sure that seems doable, though it might require changing the interfaces a bit to pass down a "syncing" flag.

**Comment by hyc** [comment]
just for reference, I'm timing a few different approaches to sync-from-scratch. Will see how big a perf difference there is. On a server with HDD, so this is going quite slowly so far.

**Comment by hyc** [comment]
I believe the default sync mode is pretty safe now with PR #1506. Should probably close this issue.

**Comment by dternyak** [comment]
Bump @luigi1111 @fluffypony - trying to help close resolved issues.

**Comment by luigi1111** [comment]
Closing (see #1506).
