### ISSUE TITLE
tests fail on arch with fresh clone

### ISSUE THREAD

**Issue by Silur** [monero-project/monero#1702]
```
>make
.....
[  PASSED  ] 674 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] Serialization.portability_wallet
[  FAILED  ] Serialization.portability_outputs
[  FAILED  ] Serialization.portability_unsigned_tx
[  FAILED  ] Serialization.portability_signed_tx

Linux 4.9.7-1-ARCH #1 SMP PREEMPT Wed Feb 1 19:33:40 CET 2017 x86_64 GNU/Linux
```

**Comment by moneromooo-monero** [comment]
Look up a bit, there will be the actual lines where a check fails for these. Please post those.

**Comment by Silur** [comment]
`2017-02-10 13:13:46.307 [SRV_MAIN]      ERROR   cn      src/cryptonote_core/cryptonote_basic_impl.cpp:105       Block cumulative size is too big: 40001, expected less than 40000`
`2017-02-10 13:13:46.307 [SRV_MAIN]      ERROR   cn      src/cryptonote_core/cryptonote_basic_impl.cpp:105       Block cumulative size is too big: 280001, expected less than 280000`
this error causes each fail, with different numbers

**Comment by moneromooo-monero** [comment]
These may be normal. I'm talking about assertion failures in the tests you mentioned.

**Comment by moneromooo-monero** [comment]
For the record, another arch user reports those tests passed.

**Comment by Silur** [comment]
checking it again

**Comment by jtorbicki** [comment]
I have the same problem. All 4 failed assertions are caused by similar issue. For instance the first one:
Serialization.cpp:684: Failure
Value of: r
  Actual: false
Expected: true
This is caused because this file is NOT found: 
string wallet_file = epee::string_tools::get_current_module_folder() + "/../../../../tests/data/wallet_9svHk1";

There is also a warning in the output: file not found "tests/unit_tests/../../../../tests/data/wallet_9svHk1.keys" 

It might mean that the result of this function call: epee::string_tools::get_current_module_folder() does not get very well with so many ../../../../ :)

**Comment by moneromooo-monero** [comment]
When this happens, what is:
- the command line used
- the directory you are running it from

**Comment by jtorbicki** [comment]
@moneromooo-monero after your comment I did some digging and I guess the problem is with the AUR package which is arch specific. I suspect this line to be causing troubles (66): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitmonero-git#n66
Probably tests should be executed from different location?

**Comment by danrmiller** [comment]
@jtorbicki Have you generated the test wallets and followed the configuration according to this document:

https://github.com/monero-project/monero/blob/master/tests/libwallet_api_tests/scripts/README.md

**Comment by moneromooo-monero** [comment]
From that file, the problem seems to be that the build tree root is build, rather than build/release. So there's one less directory to backup to find the data files.

**Comment by moneromooo-monero** [comment]
I did not know about that README. Those things should really be done automatically by the tests.

**Comment by danrmiller** [comment]
Sorry, it seems I didn't look closely enough and that configuration doesn't apply to the unit tests mentioned in this issue. But I agree that libwallet tests configuration could be done automatically by the build.

**Comment by moneromooo-monero** [comment]
This is a problem with the AUR script itself. The author will fix it when trying the tests. Please report it there.

+invalid
+resolved

**Comment by anonimal** [comment]
@jakoblind why are you using that package? It's barely maintained and the maintainer refuses to remove it. Try https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=monero.

JFTR, as noted in the package:
```
# NOTE:
#   Our latest issue appears makepkg related:
#     "file not found "tests/unit_tests/../../../../tests/data/wallet_9svHk1.keys"
#   As noted in #monero-dev:
#     2017-02-24 anonimal        Not to defend Arch or this strange makepkg issue, but for a unit-test like that, IMHO I think the stream should be decoupled from file handling so that the unit-test can process the stream directly. Then, wallet*.keys can be put into hex form within the unit file.
```
