### ISSUE TITLE
Monerod sync stalls when date changes

### ISSUE THREAD

**Issue by elelel** [monero-project/monero#2146]
It seems that monerod synchronization stops when the clock goes over 00:00. The last message in the log is like:
```
2017-07-03 23:59:33.947	[P2P6]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1004	[X.X.X.X:28080 OUT]  Synced 1251780/1346393
```

**Comment by moneromooo-monero** [comment]
That seems pretty unlikely, especially since some people report multi-day sync times.
If you still have that daemon running, please try "set_log 1" and see what you get.
In any case, in another terminal: gdb /path/to/monerod `pidof monerod`
Then, in gdb: thread apply all bt
Replace the path as appropriate in the gdb command.

**Comment by elelel** [comment]
Unfortunately I've restarted the server already. It has been working for about a day (syncing from scratch) before that, and has been in the stalled state for about 5 hours after 00:00. It has not been responding to anything, with a CPU thread loaded. Kill it with signal 9. When I restarted it, it continued without a problem.

**Comment by moneromooo-monero** [comment]
Nothing to work on here, so I'll close it. Reopen if you get a trace.

+invalid
