### ISSUE TITLE
Brazilian Portuguese supporte

### ISSUE THREAD

**Issue by EvertonMelo** [monero-project/monero#2152]
add a file language Brazilian Portuguese, 
path:  monero/translations/

**Comment by moneromooo-monero** [comment]
See the file README.i18n, which details what is needed in order to get a new language translation.
Note that this is only for monero-wallet-cli, as I think monero-wallet-gui already has a Brazilian translation (or at least a Portuguese one, which I think is kinda mixed pt/pt_BR).  Tracking for the GUI is at https://github.com/monero-project/monero-core/

**Comment by EvertonMelo** [comment]
Thank you.

**Comment by moneromooo-monero** [comment]
I'm going to close this, as it's not a bug. If you want to add a pt_BR translation, please feel free.

+invalid
