### ISSUE TITLE
Enable docker container to be run headlessly

### ISSUE THREAD

**Issue by Levino** [monero-project/monero#2360]
See [this issue first](https://github.com/monero-project/monero/issues/1598)

So one can only run the docker image in "interactive" mode. If not it fails with non comprehensible errors.

One should make sure that the docker container also runs headlessly.

**Comment by moneromooo-monero** [comment]
To run as a (non interactive) daemon, use --detach.

**Comment by Levino** [comment]
Still it feels wrong to have to attach to use `-i` or `stdin_open: true` in docker compose, to keep STDIN open even if not attached. Why is this necessary. No other daemon docker container that I know of has this requirement...

**Comment by moneromooo-monero** [comment]
I have no idea about docker, so I can't answer that.

**Comment by MoroccanMalinois** [comment]
> No other daemon docker container that I know of has this requirement...

@Levino : I'll bet than none of these daemons have a console for humans to interact with them

"Interactive" option in docker means "Keep STDIN open even if not attached".
It's distinct from the idea of foreground/background mode. So the docker container **can** run headlessly. For that, it's the docker option "-d". So, one can do : 

    docker run -i -d ....

(monerod **must not** use --detach when used inside docker)

JFTR, i've been using docker for monero for more than a year now (and on multiple hosts). Never had any pb, but i've only used mounted volumes for the data-dir. Otherwise, Docker uses [AUFS](https://en.wikipedia.org/wiki/Aufs), which doesn't look great to combine with lmdb.

**Comment by MoroccanMalinois** [comment]
Alternatively, there is also the option `--non-interactive` in monerod, so that it doesn't need to be activated at docker's level. 

    docker run -d monero monerod --non-interactive

Here is an example with opened ports and using a mounted volume

    docker run -d  -p 18080:18080 -p 127.0.0.1:18081:18081 -v /host/path/to/data/dir:/root/.bitmonero monero monerod --rpc-bind-ip=0.0.0.0 --confirm-external-bind --non-interactive

**Comment by Levino** [comment]
Starting monerod non-interactively makes the most sense for me. Will overwrite the entrypoint. Thanks for clarification. Closing this issue.
