### ISSUE TITLE
Network lost my monero

### ISSUE THREAD

**Issue by walec51** [monero-project/monero#2380]
http://imgur.com/a/9GSYF

transaction confirmed lots of times but there a NO transactions in my wallet history

**Comment by moneromooo-monero** [comment]
If you're having a problem with Mymonero, check #mymonero on freenode, or ask on reddit, or there should be a contact email somewhere on the site.

+invalid

**Comment by walec51** [comment]
I have the exact same problem in my fully synced official desktop wallet !!!
its a network problem!

**Comment by stoffu** [comment]
Don't panic, I'm pretty sure your fund isn't lost. Try opening the wallet file with the CLI.

**Comment by walec51** [comment]
same thing:
[wallet 48Pszc]: balance
Balance: 0.000000000000, unlocked balance: 0.000000000000
[wallet 48Pszc]: show_transfers
[wallet 48Pszc]:

**Comment by fluffypony** [comment]
CLI works fine, your node probably isn't caught up.

![screen shot 2017-08-31 at 4 50 29 pm](https://user-images.githubusercontent.com/1944293/29929752-a06aca46-8e6c-11e7-9804-fef4b4b08474.png)

It didn't show up in MyMonero because you didn't pay the import fee, so it only scanned for transactions from when you first loaded it into MyMonero.

**Comment by fluffypony** [comment]
I triggered a manual import on MyMonero for no charge, and your tx is showing up on the backend now.

**Comment by walec51** [comment]
Ok, many thanks. Freaked out when I didn't see it in any of the three wallets. However it is still strange that a freshly installed desktop wallet didn't pick up the transactions.
