### ISSUE TITLE
Lastest GIT FTBFS on ppc64el

### ISSUE THREAD

**Issue by madscientist159** [monero-project/monero#2473]
Trying to build latest GIT on ppc64el, got assertion error and FTBFS:

`/home/test/monero/src/serialization/json_object.cpp: In instantiation of ‘void cryptonote::json::{anonymous}::convert_numeric(Source, Type&) [with Source = int; Type = char]’:
/home/test/monero/src/serialization/json_object.cpp:76:20:   required from ‘void cryptonote::json::{anonymous}::to_int(const Value&, Type&) [with Type = char; rapidjson::Value = rapidjson::GenericValue<rapidjson::UTF8<> >]’
/home/test/monero/src/serialization/json_object.cpp:144:16:   required from here
/home/test/monero/src/serialization/json_object.cpp:54:5: error: static assertion failed: source and destination signs do not match
     static_assert(
     ^
src/serialization/CMakeFiles/obj_serialization.dir/build.make:62: recipe for target 'src/serialization/CMakeFiles/obj_serialization.dir/json_object.cpp.o' failed`

**Comment by hyc** [comment]
+duplicate
#2471

**Comment by danrmiller** [comment]
@hyc the label bot didn't take action because you aren't in the access list. I added you (https://github.com/monero-project/meta/issues/100#issuecomment-330407739). 

Its already marked this comment as seen in its db, and I think it would be easiest if I just tell it to label this instead of messing with the database, but from now on this should work for you in the monero repo.

+duplicate
