### ISSUE TITLE
Get integrated address from transaction by payment id

### ISSUE THREAD

**Issue by Arti3DPlayer** [monero-project/monero#2787]
My actions:

1) `monero-wallet-cli  make_integrated_address`
Receive: 
```
"result": {
    "integrated_address": "my_address"
    "payment_id": "my_payment_id"
  }
```

2)  Then from another wallet I send money with transfer method: https://getmonero.org/resources/developer-guides/wallet-rpc.html#transfer

3) `monero-wallet-cli  get_transefrs`
Receive
`{'payment_id': 'some_unique_payment_id', 'amount': 100}`

4) `monero-wallet-cli make_integrated_address(some_unique_payment_id)
`
5) Received new address, instead of existing one

**Comment by moneromooo-monero** [comment]
I had to do a few assumptions on what you left unsaid:

- you used monero-wallet-rpc instead of monero-wallet-cli (since make_integrated_address is a RPC)
- my_payment_id and some_unique_payment_id are the same (otherwise it doesn't make sense)
- the transfer was made to the integrated address

Given that, it works for me. I get the same address from the first make_integrated_address RPC (without a payment id) and the second one (with a payment id).

Make sure you didn't make a mistake, and if you didn't, give more precise repro steps.

**Comment by Arti3DPlayer** [comment]
@moneromooo-monero thanks for answer. Yes it was my mistake. Works well
