### ISSUE TITLE
RPC: Wrongly formatted RFC 2616/2617 header

### ISSUE THREAD

**Issue by onodera-punpun** [monero-project/monero#3059]
https://www.ietf.org/rfc/rfc2617.txt

The wallet RPC header:

```
[Digest qop="auth",algorithm=MD5,realm="monero-rpc",nonce="1b4e8/tzwgdTEPyeJ2QUDA==",stale=false Digest qop="auth",algorithm=MD5-sess,realm="monero-rpc",nonce="1b4e8/tzwgdTEPyeJ2QUDA==",stale=false]
```

`algorithm` should be `"MD5"` but is `MD5`.

This causes the vast majority of (golang) digest libraries to not work, see https://github.com/One-com/digest/issues/1 for an example.

**Comment by onodera-punpun** [comment]
+bug

**Comment by vtnerd** [comment]
Eh, the situation is the opposite. The golang libraries have the bug, and this is using the correct syntax. Here is the grammar from the RFC:
```EBNF
       algorithm         = "algorithm" "=" ( "MD5" | "MD5-sess" |
                           token )
```
If quotes were included it would be `"algorithm"=` instead of `"algorithm"=`. Or another example from the RFC:
```EBNF
       request-digest = <"> 32LHEX <">
       LHEX             =  "0" | "1" | "2" | "3" |
                           "4" | "5" | "6" | "7" |
                           "8" | "9" | "a" | "b" |
                           "c" | "d" | "e" | "f"
```
If the quotes were included you would have `request-digest="a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a""a"` as the value.

**Comment by onodera-punpun** [comment]
Eh, I tried at least 5 golang digest libs and all didn't work because of this, is everyone doing it wrong? Anyways upon closer reading you might indeed be right. I can't seem to figure out from the RFC document if they mean literal quotation marks or not.

**Comment by moneromooo-monero** [comment]
I think vtnerd's interpretation from the RFC text is the most sensible.

**Comment by selsta** [comment]
https://github.com/monero-project/monero/pull/3060#issuecomment-455600952
