### ISSUE TITLE
Don't use Google DNS

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero#3146]
Google DNS (8.8.4.4) is used to e.g. look up the seed nodes.
Why not use a more trustworthy service and stop feeding Google with the number of running nodes and their IP addresses?

Related to https://github.com/monero-project/monero-site/issues/558 which is also using a Google service.

__EDIT__:
Fix referenced issue.

**Comment by moneromooo-monero** [comment]
Feel free to suggest a better solution.

**Comment by leonklingele** [comment]
`monerod` could try to use the local resolver first (if available), use one (multiple?!) from https://wikileaks.org/wiki/Alternative_DNS
Is kovri also covering DNS given that it supports UDP?

**Comment by moneromooo-monero** [comment]
monerod uses the default resolver if you don't specify DNS_PUBLIC. You're saying you don't have DNS_PUBLIC set, your default resolver is not google's, and monerod uses google to resolve ?

AFAIK DNS will go over kovri too.

**Comment by moneromooo-monero** [comment]
Thanks, that list is useful.

**Comment by leonklingele** [comment]
Oh, I just noticed I'm defining `export DNS_PUBLIC=tcp` in my startup script. Commenting out that line "fixes" the issue. The Google IP is hardcoded here: https://github.com/monero-project/monero/blob/35d5aa36c9b2f4bba169e5947039bf7871649ee1/src/common/dns_utils.cpp#L45

**Comment by moneromooo-monero** [comment]
You can set DNS_PUBLIC=tcp://x.y.z.a if your local resolver doesn't work well with DNSSEC.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3225

**Comment by anonimal** [comment]
>AFAIK DNS will go over kovri too.

Yes, but only if a DNS server is running a server tunnel and a client tunnel is configured to connect to said server tunnel and the client tunnels DNS requests through said tunnels and only once UDP-related implementations are resolved - but there is no point in using DNS with kovri because the lookup system is [completely different](https://getmonero.org/resources/moneropedia/address-book.html).

When we integrate, we'll most likely distribute a hardcoded b32 ledger of nodes to connect to, so name resolution won't be necessary. On the other hand, namecoin is also taking an interest in kovri so something may come up in the works regarding naming solutions. TBD.

**Comment by anonimal** [comment]
>For updates and checkpoints, since the data is stored in a TXT record in DNS, how would that work then ?

I could answer this after more time learning monero. Maybe *not* store in a DNS TXT record? I don't know of an alternate solution at the moment.

>You'd change it to a set of known b32 addresses and actually hit the web servers there ?

I'm assuming so. @fluffypony gave an answer to this at some point, I think.

**Comment by moneromooo-monero** [comment]
+resolved
