### ISSUE TITLE
False Alarm. DELETE ME.

### ISSUE THREAD

**Issue by juanpc2018** [monero-project/monero#3305]
False Alarm. DELETE ME.

**Comment by leonklingele** [comment]
First off, please don't ever publicly disclosure potential security issues, follow the instructions at https://github.com/monero-project/meta/blob/master/VULNERABILITY_RESPONSE_PROCESS.md instead.

Please double — __triple__ — check that the two passwords really were different.
How did your brute-forcing procedure look like? Maybe your brute-forced the same password twice?

> also the Update does not work, but daemon asks for update.

That's a known issue and has been fixed with https://github.com/monero-project/monero/pull/3293.

**Comment by anonimal** [comment]
@juanpc2018 Responsible Disclosure is clearly documented in the file called [README.md](https://github.com/monero-project/monero/blob/master/README.md). The file is called README because it must be read.

**Comment by anonimal** [comment]
>Please file your bug report in the monero-gui repo.

@iDunk5400 This issue is in the realm of Vulnerability Response and should **not** be reported to the monero-gui repo.

**Comment by dEBRUYNE-1** [comment]
+resolved
