### ISSUE TITLE
Docker build crash

### ISSUE THREAD

**Issue by alextaaa** [monero-project/monero#3349]
I try to use `docker build -t monero .` in stable branch `release-v0.11.0.0`

But I get the error:

```
-- Could not find GNU readline library so building without readline support
CMake Error at CMakeLists.txt:847 (message):
  Could not find required header zmq.hpp


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/monero/build/release/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/monero/build/release/CMakeFiles/CMakeError.log".
Makefile:68: recipe for target 'release-static' failed
make: *** [release-static] Error 1
The command '/bin/sh -c make -j$(nproc) release-static' returned a non-zero code: 2
```

**Comment by moneromooo-monero** [comment]
I see no crash here.

As for your build error, install zmq.hpp.

**Comment by alextaaa** [comment]
But I use the Dockerfile `https://github.com/monero-project/monero/blob/release-v0.11.0.0/Dockerfile`

Could you plz include all required command (like this `install zmq.hpp`) for successfully build?

**Comment by MoroccanMalinois** [comment]
@alextaaa The Dockerfile you are using is pulling code from branch master (even if you cloned from another branch), and zmq has been added since v0.11.0.0. 

So easiest solution is to just add ` -b release-v0.11.0.0` to https://github.com/monero-project/monero/blob/release-v0.11.0.0/Dockerfile#L19.

Or you could use branch `master` with #3316 (whose Dockerfile include commands to rebuild all dependencies, but it will probably not work with branch v0.11 because of the `-fPIC` build).

**Comment by homdx** [comment]
My commit is fix you issue?
https://github.com/monero-project/monero/pull/3879

**Comment by moneromooo-monero** [comment]
I'll call that fixed since several people built this since the fix.

+resolved
