### ISSUE TITLE
multisig signing error

### ISSUE THREAD

**Issue by egonson** [monero-project/monero#3447]
I signed multisig tx and I lost the tx_data_hex. So I signed again, but I met the error.

curl -X POST --digest --user "monero:monero" http://127.0.0.1:18083/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"sign_multisig","params":{"tx_data_hex":"[transfer result multisig_txset]"}}' -H 'Content-Type: application/json'
{
  "error": {
    "code": -35,
    "message": "Failed to sign multisig tx: This signature was made with stale data: export fresh multisig data, which other participants must then use"
  },
  "id": "0",
  "jsonrpc": "2.0"
}

question.
How can I sign multisig tx again? or how can I get the previous signed tx data?

**Comment by moneromooo-monero** [comment]
The message says it: export multisig info, and import it. You can't sign twice with the same info, as it woul open up a vulnerbility.

**Comment by rbrunner7** [comment]
If you say *You can't sign twice with the same info*, what is this "info" that you refer to? The state of the wallet, as produced by the last executed `import_multisig_info` command?

Is the consequence of this that you never can have 2 or more multisig transactions "in transit", that you must fully do one after the other strictly in sequence, with an obligatory exchange of "multisig_info" in between?

I guess so, because what I did to get the same error was a crystal-clear sequence of actions with the CLI wallet:

- `transfer` in wallet A, rename `multisig_monero_tx` to `multisig_monero_tx_1` to avoid overwrite
- `transfer` again in wallet A to start a second transaction right away
- `sign_transfer` in wallet B, with the first file `multsig_monero_tx_1`
- `sign_transfer` again in wallet B, with the second file `multisig_monero_tx`

That last action then leads to the error that the OP also got:

*Error: Multisig error: This signature was made with stale data: export fresh multisig data, which other participants must then use*

**Comment by moneromooo-monero** [comment]
Yes to all (theoretically you could modify the wallet to export/import lists of such L/R data instead of one per at a time).

**Comment by moneromooo-monero** [comment]
Seems to work as designed, you can't sign twice with the same data.

+invalid
