### ISSUE TITLE
Will 'unspent_outputs' json rpc be implemented?

### ISSUE THREAD

**Issue by egonson** [monero-project/monero#3565]
I need 'unspent_outputs' json rpc method to manage outputs (consolidating, dividing...).
I saw wallet-cli supports that command.
I must know when i should sweep the changes. To do so, I need the method to list all unspent outputs in program.
Or is there any other method?

**Comment by moneromooo-monero** [comment]
You're looking for "incoming_transfers", with the "available" transfer type.

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by gituser** [comment]
I've just stumbled across same issue that there is no `unspent_outputs` equivalent for RPC.

And, no `incoming_transfers` with `available` transfer_type isn't solving the issue, because it will not show you block number and number of keys in that block number, instead it will show you some internal `global_index` instead.

I've looked into the code and it uses some internal flag `m_spent` here from RPC `get_transfers` method instead in the `unspent_outputs`: https://github.com/monero-project/monero/blob/master/src/simplewallet/simplewallet.cpp#L6881

I wasn't able to reproduce fully cli method `unspent_outputs` via RPC call `incoming_transfers` or `get_transfers` to get similar output.

Maybe you could just add block number into the output of `incoming_transfers` ?
