### ISSUE TITLE
Someone know what this Error means?

### ISSUE THREAD

**Issue by dmgmaker** [monero-project/monero#3621]
It happens when i try to get into my wallet with my password.
![unbenannt](https://user-images.githubusercontent.com/38203374/38684770-b2d3e118-3e70-11e8-8211-09b3dbbb433a.jpg)

**Comment by dmgmaker** [comment]
Or can someone explain to me why remote node isnt working? I got rid of the first error by restoring my wallet. 
![unbenannt](https://user-images.githubusercontent.com/38203374/38685051-54e4c206-3e71-11e8-8617-bdaf9ca5d342.jpg)

**Comment by stoffu** [comment]
The red text at the top right of the balance section means that you unintentionally chose stagenet when restoring the wallet, which is why you can't connect to node.moneroworld.com:18089 and your balance is zero. Do the wallet restoration process again, and make sure that neither of the "testnet" or "stagenet" checkboxes is checked at the very first "Welcome to Monero" screen.

**Comment by dmgmaker** [comment]
What is the Mode stagenet and testnet for? But thank you very much this helped me to get my wallet to work. I have one little more question i thought that when i use remote node that it will be ready instantly but it needed like one hour to finish (it was no problem because i try to get it working since 5 days)

**Comment by stoffu** [comment]
The testnet and stagenet are for testing the software without having to spend real money.

Regarding remote node: if your wallet’s restore height is sometime back in the past, the wallet still needs to download and scan those blocks which can take a while.

**Comment by moneromooo-monero** [comment]
+invalid
