### ISSUE TITLE
SpendProof "Invalid signature size" / no further documentations

### ISSUE THREAD

**Issue by codexx420** [monero-project/monero#3761]
Hello!
I'm working a lot with the monero cli/rpc tools. Recently, the beautiful developers added a function to prove spent transaction without the need of the tx key/view key. Sadly, all of the generated SpendProofs are not working. I'm getting "Error: incorrect signature size" when I check the spendproofs with the check_spend_proof cli command.
I'm **not getting this error** if I generate the spent proof with the same wallet binaries and local bitmonero files (e.g. chain data).
But when I use separate local bitmonero files, it won't work.  (Incorrect signature size). 

Are there any documentations or informtion to that or am I missing something?

**Comment by stoffu** [comment]
Admittedly it's not documented well; the code is the only documentation at the moment.

The most likely cause of your problem is that you put some additional character (probably newline) to the file that stores the signature data (the equivalent of `monero_spend_proof` file generated with the CLI wallet). The file must not contain any additional characters.

**Comment by itssteven** [comment]
As far as I can see, this happens if you check a different txid than the one which was used to create the signature.

I'm using this temporary fix to overcome the issue when working with monerophp: https://github.com/monero-integrations/monerophp/pull/74

It's as if the code checks what the valid length for the signature would be with the txid you provide and returns an error rather than a signature=bad return.

**Comment by stoffu** [comment]
@itssteven 
> As far as I can see, this happens if you check a different txid than the one which was used to create the signature.

Yes, the signature size is in proportion to the number of inputs and the ring size, which means it can become quite large sometimes, which is why the CLI writes the signature to a file instead of displaying it on the console.

**Comment by codexx420** [comment]
Hello,
thanks for the fast answers! you're awesome. of course it was that issue:
> The most likely cause of your problem is that you put some additional character (probably newline) to the file that stores the signature data (the equivalent of monero_spend_proof file generated with the CLI wallet). The file must not contain any additional characters.

A small note: using nano (even by deleting the last line) and ```echo "SpendProofV1..." > file ``` creates a newline char at the end of the file. Now it worked!

**Comment by itssteven** [comment]
@stoffu 
> Yes, the signature size is in proportion to the number of inputs and the ring size, which means it can become quite large sometimes, which is why the CLI writes the signature to a file instead of displaying it on the console.

No, that's not my issue. When checking the spend proof, if it's checked with a txid the spendproof wasn't signed with, it returns an error rather than a "signature=bad" as it would if you checked an invalid spendproof. This is fine for the CLI because it makes no difference to the user, but when using the RPC you will get an error rather than a "signature=bad" return. There should be no error, as far as I can see.
