### ISSUE TITLE
Wallet RPC: add address index filter to get_balance

### ISSUE THREAD

**Issue by artyomsol** [monero-project/monero#4168]
In case of hundreds / thousands / millions of managed subaddresses the `get_balance` response of the RPC API will become a huge JSON as of current implementation.
 An `address_index` parameter (array of unsigned int; (Optional) List of subaddress indices to return from an account) should be added to optionally filter the "per_subaddress" array of the method response.
 Totals for the account balance ("balance"  and "unlocked_balance") should be calculated for the all of subaddresses despite of the filter parameter specified.

**Comment by stoffu** [comment]
#4171

**Comment by stoffu** [comment]
I've closed #4171 because it was tailored to the wrong use of subaddresses: if you need to issue millions of subaddresses to handle many users' deposits, you should use the `create_account` command for each user. Accounts are meant for managing individual users' balances, while subaddresses within the same account (i.e. having the same major index) are meant to be used for issuing one-time throwaway addresses (i.e. ShapeShift scenario in #2056).

**Comment by artyomsol** [comment]
@stoffu Sorry but your doubt  is irrelevant to the issue you've solved. It does not matter  what fore wallet owner need to create millions of subaddresses. Having ShapeShift scenario you will face a trouble when `get_balance` will return ALL subaddresses in response all the time. While you will be interesting in some limited set of recently issued throwaway addresses.

**Comment by stoffu** [comment]
> Having ShapeShift scenario you will face a trouble when get_balance will return ALL subaddresses in response all the time. 

This is not the case unless you only receive funds and never spend them; when spending them, the change goes back to the base address (minor index = 0) such that the funds accumulate in the base address.

Anyway, I reopened #4171 as it doesn't change the default behavior and seems harmless.

**Comment by moneromooo-monero** [comment]
+resolved
