### ISSUE TITLE
Failed sending transaction: ge_frombytes_vartime failed at 286

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#5244]
Hi. 

After updating to `v0.14.0.1` one of the transactions failed for some reason with the error:
`ge_frombytes_vartime failed at 286`

I've found related issue - https://github.com/monero-project/monero/issues/1971 not quite sure if it's the same so I'm creating a new one.

Not sure why or what could be wrong as it happened for the first time after the update, no monero has been spent though in the result.

Also might be related - https://github.com/monero-project/monero/issues/4766#issuecomment-470333731 

After setting the `ulimit -l $((64*1048576))`, restarting wallet-rpc and re-sending the transaction it all worked just fine and transaction has been created.

The recipient is a regular monero address.

The log of wallet-rpc is below:
[Log](https://paste.fedoraproject.org/paste/KO16Fyw6j9J7vqGpNvlefA/raw)

**Comment by moneromooo-monero** [comment]
It looks like the problem is that your transaction picked an output on the chain with an invalid public key. This means someone sent an invalid monero tx at some point, and you tried to include it in a ring, and ring creation failed since that output is invalid. This is one of the lines where you replaced a number with "some number". These are not your outputs, but the ones the wallet selected to use as part of your ring. If you want to share them, I can write some code to fetch them and verify that one of them is indeed invalid.

The "Error locking page" errors are unrelated, and are not fatal.

**Comment by gituser** [comment]
There you go:

[log](https://paste.fedoraproject.org/paste/EADTuJCrk7TBTa3WE1bu7w/raw)

**Comment by moneromooo-monero** [comment]
Indeed, you picked 8950023, with pubkey cf631ae3691888e0d858e79bd6b37f1915493789bab4f85cf12bf001d4d86a04, which is not in the main subgroup. I will patch the wallet so these are automatically discarded.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5248

**Comment by gituser** [comment]
Happy to close this issue once this goes into the new release and there is a confirmation that fix is working.

Thanks.

**Comment by moneromooo-monero** [comment]
+resolved
