### ISSUE TITLE
UI broken for restoring hardware wallet

### ISSUE THREAD

**Issue by Belkaar** [monero-project/monero#5469]
Client: monero-wallet-gui v0.14.0.0
OS: Windows

* Select "Create new wallet from hardware"
* Select "Restore a wallet from device."

The UI breaks and you can't enter the wallet creation heigt.

![HWwalletUiProblem](https://user-images.githubusercontent.com/2395990/56453757-1bb22b80-6347-11e9-9a4b-cbe2f4ea447e.png)

**Comment by dEBRUYNE-1** [comment]
We're aware of this issue. It will be fixed in the upcoming release. In the meantime, you should be able to use this work around:

>There is a fix for the time being: You can access the restore height window by selecting the wallet location and pressing tab once.

**Comment by erciccione** [comment]
@Belkaar This is the wrong repo. This issue should have been opened in monero-gui.

@fluffypony @luigi1111 There is a new GitHub feature which allow to transfer issues to another repo (https://help.github.com/en/articles/transferring-an-issue-to-another-repository). That could be used instead of closing and reopening this issue.

**Comment by Belkaar** [comment]
@erciccione Sorry for choosing the wrong repo. Feel free to move the issue, i don't seem able to.

**Comment by dEBRUYNE-1** [comment]
@Belkaar - I'll close it if you confirm that the work around I posted works.

**Comment by Belkaar** [comment]
@dEBRUYNE-1 - Yes, the workaround did work.

**Comment by dEBRUYNE-1** [comment]
All right, going to mark this as resolved then.

**Comment by dEBRUYNE-1** [comment]
+resolved
