### ISSUE TITLE
long payment id is truncated

### ISSUE THREAD

**Issue by xinyijun** [monero-project/monero#5593]
I created a transfer using RPC "transfer" with payment id "223ef04ab3eb525b000000000000000000000000000000000000000000000000", and then call RPC "get_transfers", the payment id returned was truncated to the first 16 non-zero characters. It seem that the payment id will be truncated if the it ends with 48 '0'.

**Comment by moneromooo-monero** [comment]
Yes. It is intended. Is this annoying ?

**Comment by xinyijun** [comment]
Thanks for the quick reply, it seems to be strange, is there any reason to do this? Our audit failed in this case.

**Comment by moneromooo-monero** [comment]
The reason is that short payment ids were added after long ones, and use the same system, but they're shorter, so they're padded with zeroes internally.

You should not use long payment IDs anyway. they're obsolete, and support for them may be removed soon. Subaddresses is the best thing to use, and integrated addresses (short encrypted payment IDs) a second choice.

**Comment by xinyijun** [comment]
Ok, thanks.
