### ISSUE TITLE
android build

### ISSUE THREAD

**Issue by Fapt4ov** [monero-project/monero#5768]
hi

build for android failed on iconv

i followed the guide nothing special

docker build -f android.dockerfile -t monero .

"cconfigure: error: in `/opt/android/libiconv-1.15':
onfigure: error: in `/opt/android/libiconv-1.15':
configure: error: C compiler cannot create executables"

there is no other error mesage only

"WARNING: using cross tools not prefixed with host triplet"

i change version to 1.16 but same error.

**Comment by hyperreality** [comment]
The issue is that libiconv is trying to link against libtinfo5, which does not exist on Debian Buster by default. Since Debian stable was upgraded from Stretch->Buster a month ago, it appears that libtinfo6 is now the default installed version. However libtinfo5 is still available in the repos.

I have added it and tested that the Android build now works in the referenced commit.

**Comment by Fapt4ov** [comment]
HELLO!

Very good.

Issue solved.
