### ISSUE TITLE
can multi monerod r/w the same lmdb blockchain at the same time with different tor ip address？

### ISSUE THREAD

**Issue by mangomining** [monero-project/monero#6137]
I have some node run monerod trust each other and want to use the same monero blockchain lmdb file with NFS or other ways，at the same time，every monerod node own different tor ip，can achieve it？ in this way，we can create a lot of full nodes with different tor ip address. （effect is that you know there is many full nodes but you dont know accurate full node number）

**Comment by moneromooo-monero** [comment]
monerod will not run on NFS, unless some fancy version that has mmap support. Otherwise, a blockchain can be used by more than one monerod at the same time, though I doubt it's tested much.
Note that if two nodes work on the same db, they'll have the same blockchain state at all times, and that can be a way to link two tor peers if they never have some jitter in their update timing (probably requires constant active probing though).

**Comment by mangomining** [comment]
thanks for reply my preliminary idea，i will do some test by self when 0.15 released.

**Comment by hyc** [comment]
0.15 was already released a few days ago. https://github.com/monero-project/monero/releases/tag/v0.15.0.0

Note: NFS *has* mmap support. But it doesn't guarantee cache coherency, which is what LMDB requires. AFAIK there are no remote filesystems that do.

**Comment by moneromooo-monero** [comment]
No bug here.
