### ISSUE TITLE
E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon

### ISSUE THREAD

**Issue by NoBugBoy** [monero-project/monero#6169]
For example, I use the following command to start RPC. If this exception occurs, how can I solve it.
DNS_PUBLIC=tcp://8.8.8.8 ./monero-wallet-rpc --rpc-bind-port=38089 --rpc-login=test:123456 --wallet-file=/wallet/xmr/newwallet.keys --password=bib123 --rpc-bind-ip=0.0.0.0 --confirm-external-bind，

error logs:
2019-11-22 08:49:04.759 E No message store file found: /wallet/xmr/newwallet.keys.mms
2019-11-22 08:49:04.760 E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon
2019-11-22 08:49:04.760 E Wallet initialization failed: no connection to daemon

**Comment by moneromooo-monero** [comment]
Run a daemon.

If you are running one on the same machine with default settings, then it seems like a bug.

Otherwise, this is a bug tracker, not a user help forum. Please ask on Freenode in #monero, or reddit, or bitcointalk.org.

Are you running a daemon on the same machine with default settings ?
