### ISSUE TITLE
transfer command return very large data？

### ISSUE THREAD

**Issue by GongSuiLi** [monero-project/monero#6490]
When my program uses the command to call the Monero so file and transfer 0.0001 Monero, the unsigned transaction data returned is particularly large, even 16Mb. I tried to transfer xmr with different amounts, the size of the transaction data returned is still 16Mb, what is the reason?

**Comment by moneromooo-monero** [comment]
Since you say "unsigned", you're using the cold/hot wallet system, right ? If so, the transfer files also include new output data (from hot wallet to cold wallet) and key images (from cold wallet to hot wallet). If you make another payment, the file should be smaller as it's already transfered most output data.
