### ISSUE TITLE
how to debug monero on Win7?

### ISSUE THREAD

**Issue by jiebanghan** [monero-project/monero#6814]
My aim is to learn the codes of monero so I build monero in MSYS2 on Win7. And my aim is also debug it and set some breakpoints and so on in order to trace the codes of monero.But I am not ready to use gdb because I like GUI mode to debug. So how to meet my conditions with some GUI IDE? Thank you very much with all my heart.
By the way , why compile monero in msys2 so slowly? It almost consume 1 hours  or more to make.

**Comment by selsta** [comment]
Look into CLion

**Comment by jiebanghan** [comment]
thank you @selsta

**Comment by xmrdsc** [comment]
`-DCMAKE_RELEASE_TYPE=Debug` will include debugging symbols and whatnot, so you can use you a debugger to step through the code.

CLion is nice because it picks up on your `CMakeLists.txt` contents and parses the various targets, that you then can compile in debug mode - with it's integrated debugger.

**Comment by jiebanghan** [comment]
OK,  thank you @xmrdsc
