### ISSUE TITLE
The Real webcam cover inventor

### ISSUE THREAD

**Issue by MyGithubusercontents** [monero-project/monero#7165]
Ok I never messed with computers much. But oct 2019 I submitted the idea for webcam covers to InventionLand and the breached my NDA and then all year iv been harrassed by hackers because the USPTO was hacked

**Comment by MyGithubusercontents** [comment]
I have named everything I could myusercontents because I purchased myusercontents.com from godaddy and shopify stole it 3 times via myusercontents.myshopify.com

**Comment by moneromooo-monero** [comment]
Fuck you ^_^

**Comment by MyGithubusercontents** [comment]
Im tired of all this the patent office told me to learn to file how can I concentrate with all iv been through patents wrote I just cant seem to file it

**Comment by MyGithubusercontents** [comment]
who are you

**Comment by 00-matt** [comment]
Or some would have it some "critics" with no internet access hack the site and then claim our patents have been violated. Now I'm broke, missent the next patent for something different and it will take 4 more years to make a new one. Fucking hacks can't even fucking spell usernames right now. Just for that I don't wish anyone well this holiday. xXHughShacklesXx Don't want to give an f-bomb here and now because there are children listening but f**k you too, you scummy piece of shit.

when i finish my rewrites i just don't want to file now even though it is made sense for the phone num in the box to win with just the proper rollout. I did get my phone on its way yesterday but can't wait for a bigger storage problem in my part of the country where people have no heat or food and have no money and no gas for heat but people are collecting all the free stuff and i know you have got your share and want to pay it forward you are just to afraid to do so. That's all for now

— Megatron-11b (https://app.inferkit.com/demo)
