### ISSUE TITLE
[feature] Add gRPC wallet interface

### ISSUE THREAD

**Issue by vdero133** [monero-project/monero#7408]
Opening this issue to discuss and track a potential addition of a gRPC wallet interface.

Some discussion has already happened on [on reddit](https://old.reddit.com/r/Monero/comments/l6fxkl/gauging_interest_grpc_api/) and IRC/matrix.

The basis for this would be to unify the functionality of unary RPC calls and pub-sub ZMQ messages into a single interface. The interface proposed is minimal, as the scope of it would be to ease integration but not replace the JSON-RPC or ZMQ APIs.

I believe gRPC would achieve this by: 

- Provide a single dependency and framework to work with for synchronous and asynchronous calls.
- Enable more granular payment notifications.
- Possibility to combine documentation to the interface definition.
- Extended wallet client library support to all languages supported by gRPC.
- Autogenerated documentation.

In terms of risks:

- New dependency on the gRPC plugin for the protoc compiler (protobuf already being a dependency for trezor support).
- Reliance on Google maintaining the library/plugin.

Potential questions that may arise:

- Authentication can be done via [TLS](https://grpc.io/docs/guides/auth/)

Submitted  #7409 for initial feedback before going further.

**Comment by vtnerd** [comment]
This is another serialization format _and_ rpc layer. I think the negatives outweigh the benefits.

* The scheme is less supported in other systems than HTTP-JSON-RPC
* `protobuf` is one of the most irritating formats - its not self-describing and the output of objects/structs (basically) has to be buffered to write the variable-length size field before the object. Whereas the ZeroMQ code already "streams" outputs to JSON, and the HTTP (epee) code could do the same with some (slightly painful) refactoring. This has a big impact on performance because many binary values have to be sent for wallet processing.
* `protobuf` injects its auto-generated structures into codebases, so now there's a third copy (ZeroMQ and HTTP already could use a good merging). I'm closer to providing a "slice" concept to the epee serialization code so that even when copies are necessary its just a ref count change. The `protobuf` code enforces `std::string` in both directions in the auto-generated code. FWIW ZeroMQ code, which uses rapidjson for reading in, probably has this limitation with its DOM (assuming it can't be templated to something else).


> Provide a single dependency and framework to work with for synchronous and asynchronous calls.

You'd have to expand on this. ZeroMQ can do all of the stuff gRPC is doing at the protocol layer (afaik - see ROUTER/DEAER sockets), but gRPC might have built-in mechanisms for async callbacks in the language of choice.


> Possibility to combine documentation to the interface definition.

This is possible in our current approach too, but credit to gRPC for already written code.

> Enable more granular payment notifications.

I'm not sure what you mean. `monerod` does not handle anything wallet related. Most of the wallets are built around `wallet` which manages one wallet at a time. ZeroMQ could be added to the wallets but has not. 

The subscription topics for PUSH events are strings and the server side can read them in a `XPUB` socket. So the PUSH "topics" do not have to be fixed in advance. The work on the client side is generating the "topic" string - `json-wallet-watch-ADDRESS`, etc. A little funky, but async and still basic work for clients to implement. The client just has to pass that string to a ZeroMQ function in their language.

> Extended wallet client library support to all languages supported by gRPC.

ZeroMQ is already supported by many languages, does the bulk of the work for RPC and PUSH calls for clients, and is agnostic to the internal format. We use JSON which is widely supported. Switching to gRPC means it auto-generates code structures that then have to be glued to the rest of the system - there's no realistic time savings generally. You either map a DOM or map this custom protobuf thing.

> Autogenerated documentation.

The auto-documenting feature presumably only lists field names and their types. Some (actually not terrible) modifications to the epee code should allow that without an additional format+rpc dependency. Although a benefit to gRPC because it's already written code.

**Comment by iamamyth** [comment]
Regardless of one's opinion on the existing interfaces, adding another one seems a poor option, as it creates additional maintenance burdens. If you want a gRPC interface, why not just proxy it? That way, you can work towards a stable and useful interface, and if, and when, said interface becomes compelling enough, perhaps it can be added to the daemon, though I am skeptical that point will ever be reached.

**Comment by iamamyth** [comment]
After inspecting the description of the motivation on reddit, if your concern is poor documentation for existing interfaces, why not just improve their documentation? The proxy route would be a forcing function: Anything the proxy uses should be well-documented, and the proxy implementation can rely on that documentation.

**Comment by vdero133** [comment]
Had not considered those two downsides, probably down to me not being too familiar with how the other two protocols work. Protobufs seems inferior on that side from your points, I cannot comment on this myself, most of the benchmarks I've seen seem to put protobuf ahead in speed but I'm not sure how it translates to our context. I think this is a good idea mostly for ease of use.


> > Provide a single dependency and framework to work with for synchronous and asynchronous calls.
> 
> You'd have to expand on this. ZeroMQ can do all of the stuff gRPC is doing at the protocol layer (afaik - see ROUTER/DEAER sockets), but gRPC might have built-in mechanisms for async callbacks in the language of choice.

Currently if you want to perform payment processing directly from the wallet with async capabilities, you might need a subset of JSON-RPC calls for fetching balances/sending transfers/other unary calls, a --tx-notify callback script to keep track of incoming/outgoing transactions (which requires the consumer of the wallet APIs to have an HTTP server running), and if you want to batch transactions, also a callback to the daemon or use ZeroMQ (another messaging protocol). 

From my own testing , this setup is a bit brittle (granted, it may be lack of competence on my part). Its also additionally difficult if you want to run the wallet/daemon and your consumer application on different machines (additional firewall config etc).

If one wants to avoid the callbacks/ZMQ usage, a polling model needs to be used with the RPC methods, which in my opinion is inferior. Depending on scenarios, this polling might add unnecessary load to a wallet (not informed enough to quantify this).

> > Possibility to combine documentation to the interface definition.
> 
> This is possible in our current approach too, but credit to gRPC for already written code.
I am not familiar with the current process for RPC/ZMQ, but from working on the linked PR, a couple of methods are out of date on the RPC side ("strict" flag for balance methods / new_account "count"). Haven't found the ZMQ documentation, and I wouldn't feel confident writing it since the protocol is entirely new to me.
This may be opinionated, but I think if documentation is "difficult" to update (which may just mean its in a different repo), it will eventually fall behind.
> 
> > Enable more granular payment notifications.
> 
> I'm not sure what you mean. `monerod` does not handle anything wallet related. Most of the wallets are built around `wallet` which manages one wallet at a time. ZeroMQ could be added to the wallets but has not.
> 
> The subscription topics for PUSH events are strings and the server side can read them in a `XPUB` socket. So the PUSH "topics" do not have to be fixed in advance. The work on the client side is generating the "topic" string - `json-wallet-watch-ADDRESS`, etc. A little funky, but async and basic work for clients to implement. The client just has to pass that string to a ZeroMQ function in their language.
> 
This is the main use-case where a gRPC interface would reduce the barrier of entry. The gRPC interface would offer unary RPCs already existing in the JSON-RPC interface (which we could clean up of legacy fields), and additionally server-side "notifications" by hooking onto wallet2 callbacks ("on_money_received","on_new_block" being of interest here in my opinion). Bidirectional streaming would also allow for interactive transfer capabilities, with a similar workflow to the CLI (I believe the java and javascript client libraries offer something similar, this would enable to make it standard across clients).

In this manner, the consumer of the API would not need access to the daemon to receive block notifications, and in the "subscription" message of the server-side streaming rpc, additional parameters could be added (ie: filter by address, quantity etc).
There's possibility for more uses, but those two were the main ones I found difficult with the current interfaces.

The "only" thing additional this proposal adds is getting wallet notifications without using --tx-notify. Practically, I think it would ease integration time significantly.

> > Extended wallet client library support to all languages supported by gRPC.
> 
> ZeroMQ is already supported by many languages, does the bulk of the work for RPC and PUSH calls for clients, and is agnostic to the internal format. We use JSON which is widely supported. Switching to gRPC means it auto-generates code structures that then have to be glued to the rest of the system - there's no realistic time savings generally. You either map a DOM or map this custom protobuf thing.
> 
An advantage here is that serialization (granted,inferior) and RPC are defined in the same place, essentially there's a single place to look to find out what the API provides (and how) and how is the message structured. For the time being the wallet lacks the ZMQ interface, and I haven't been able to find documentation for the daemon (again, probably incompetence on my side).

> > Autogenerated documentation.
> 
> The auto-documenting feature presumably only lists field names and their types. Some (actually not terrible) modifications to the epee code should allow that without an additional format+rpc dependency. Although a benefit to gRPC because it's already written code.
From usage of the protoc-gen-doc plugin, additional info can be added to each field in leading comments. The entire RPC API documentation could be embedded within the protofiles themselves and generated at build time (more of a nice to have than a requirement).


I've considered the option to proxy the interfaces/shell callbacks, and while this would reduce new code added, AFAIK the wallet RPCs /shell notification callbacks don't expose the full functionality of wallet2. I would be willing to write documentation for JSON-RPC/ZMQ but I am not familiar enough with the ZMQ protocol to do this, I'm not sure either what the process is, but this does not address the use case IMO.

The scope I planned for this is significantly smaller than the RPC API or ZMQ, in my view.

I would be willing to maintain this interface so long that it does not grow in scope, I would be doing this part-time. 

Forgot to mention, I would be in favor of making the gRPC server (and dependency) an optional build target (disabled by default).

Feedback is appreciated if any of my assumptions are wrong, as it currently stands I do think something is needed to make async call back usage easier with the wallet.

**Comment by salty-edamame** [comment]
I'm in favor of adding a gRPC interface here because it will reduce the effort required to create, debug and keep client libraries up to date with monero-wallet-rpc changes.

If you try searching the web for "monero wallet {{popular favorite language}}" you'll find a graveyard of abandoned Github repos. A lot of them have pretty bad security flaws too.

Being able to effortlessly create & update client libraries in 10+ languages when a monero-wallet-rpc change is made would be incredible powerful. Getting secure RPC for all generated client languages is another massive plus.

**Comment by iamamyth** [comment]
> I'm in favor of adding a gRPC interface here because it will reduce the effort required to create, debug and keep client libraries up to date with monero-wallet-rpc changes.

To my knowledge, the JSON RPC interface should be backwards compatible. So, how does another interface reduce upkeep? As for creating and debugging libraries in new languages, as has already been observed in this thread, JSON RPC is probably the most widely supported option. If you're comparing gRPC to ZMQ, then perhaps you're correct regarding new language integration, but then you should at least clarify the intended scope of your comparison.

> If you try searching the web for "monero wallet {{popular favorite language}}" you'll find a graveyard of abandoned Github repos. A lot of them have pretty bad security flaws too.

I don't see how this observation is germane to the matter at hand; one could almost certainly make the same statement about literally every project with a decent-sized community.

> Being able to effortlessly create & update client libraries in 10+ languages when a monero-wallet-rpc change is made would be incredible powerful. Getting secure RPC for all generated client languages is another massive plus.

This seems nearly a contradiction with your prior argument. Auto-generated bindings merely create the illusion of a seamless upgrade; in reality, if the server changed in some backwards-incompatible way, there's a good chance the client needs more than a simple serialization update. In other words, the ability to one-command "upgrade" the client *increases* the likelihood of subtle client bugs, as compared to such scenarios forcing a breakage the user must spend some time to address.

As for security, it's not as if gRPC inherently makes anything more secure. Security is a process, not a feature, and the attitude "well it's maintained by a large corporation so it must secure" is anathema to said process.

**Comment by iamamyth** [comment]
> Forgot to mention, I would be in favor of making the gRPC server (and dependency) an optional build target (disabled by default).

Unfortunately, optional build targets have a tendency to become mandatory: If the optional target has dependencies, and developers have these dependencies installed on the build machine (which they likely will, so as to test compatibility with the optional target), then the non-optional targets will compile, even if they're broken without said "optional" dependencies. So, you end up having to run two sets of CI builds, with and without the "optional" components, to confirm the optional components really are optional. Otherwise, a lot of developers won't test the "without extras" build (a similar problem has manifested in the past with preprocessor directives, where one side of a branch had been broken for ages because no one ever tested it, and it was effectively abandoned).

**Comment by salty-edamame** [comment]
> To my knowledge, the JSON RPC interface should be backwards compatible. So, how does another interface reduce upkeep?
If the client is auto-generated, there's no upkeep required for client library maintainers.

> As for creating and debugging libraries in new languages, as has already been observed in this thread, JSON RPC is probably the most widely supported option
I'm not questioning the robustness of the RPC server or protocol, but of the client library implementation. A compiler is going to make a lot less errors than a human creating a client library.

> I don't see how this observation is germane to the matter at hand; one could almost certainly make the same statement about literally every project with a decent-sized community.
That's literally the entire point of this thread. There aren't any client libraries for many of the popular languages out there, and if there are some, they're unmaintained. Using gRPC fixes this, because there's nothing to maintain. The gRPC compiler generates those clients.


>This seems nearly a contradiction with your prior argument. Auto-generated bindings merely create the illusion of a seamless upgrade; in reality, if the server changed in some backwards-incompatible way, there's a good chance the client needs more than a simple serialization update. 

Just because the client is automatically updated doesn't mean it gets automatically updated in the user's project. 
Genuine question: have there been any breaking changes in monero-wallet-rpc? I only know of new endpoints added to change the behavior or change the data returned.
GRPC also has versioning support - that means you should never get unexpectedly different values returned.
 
>In other words, the ability to one-command "upgrade" the client increases the likelihood of subtle client bugs, as compared to such scenarios forcing a breakage the user must spend some time to address.
I don't understand how this is different than the existing situation where the JSON values returned are different

>As for security, it's not as if gRPC inherently makes anything more secure. Security is a process, not a feature, and the attitude "well it's maintained by a large corporation so it must secure" is anathema to said process.
Your straw-man argument aside, the reason why gRPC encourages better security is because it comes with TLS/ encryption capabilities- in **all clients**. I encourage you to search for monero-wallet libraries to see how many of them have clear-text HTTP hard-coded.

**Comment by salty-edamame** [comment]
> Forgot to mention, I would be in favor of making the gRPC server (and dependency) an optional build target (disabled by default).

I agree with @iamamyth, if we're going to add this, it shouldn't be an optional build target

**Comment by iamamyth** [comment]
> I'm not questioning the robustness of the RPC server or protocol, but of the client library implementation. A compiler is going to make a lot less errors than a human creating a client library.

This seems rather silly, given what you (rightly) point out below, namely, JSON deserialization isn't magically going to break tomorrow. I will grant that, esp. in statically typed languages, the auto-generated gRPC serialization and deserialization saves a bit of work. 
  
> I don't understand how this is different than the existing situation where the JSON values returned are different

It isn't necessarily any different; I was addressing both sides of your somewhat contradictory claims without granting either. JSON RPC should be backwards compatible, so there's no work in keeping the client up to date, unless a transaction protocol hardfork occurs, in which case the client tends to break as the underlying data makes no sense. However, if the gRPC interface doesn't make a backwards-compatibility guarantee, which it might not, as it's quite new, has a limited audience, and backwards-compatibility can be costly, then it there would be a difference here, making JSON-RPC clients more stable. So, your best-case scenario is a tie.

> Your straw-man argument aside, the reason why gRPC encourages better security is because it comes with TLS/ encryption capabilities- in all clients

We'll probably not come to agreement on this one, for all sorts of reasons. "Uses TLS, seems secure!" tends to be exactly a manifestation of the process vs. feature issue. For example, if both processes run on the same box, and the private key can easily be accessed, TLS buys you nothing but wasted cycles. The user actually has to pay some attention to the TLS config for it to be helpful. "Plug in this library and you're done" falls at the opposite end of the spectrum from "pay attention".

**Comment by vtnerd** [comment]
Unfortunately this seems to be - "this one use case I found might be easier in gRPC". And I doubtful about that.

> Had not considered those two downsides, probably down to me not being too familiar with how the other two protocols work. Protobufs seems inferior on that side from your points, I cannot comment on this myself, most of the benchmarks I've seen seem to put protobuf ahead in speed but I'm not sure how it translates to our context. I think this is a good idea mostly for ease of use.

Some of the code (daemon<->wallet) uses a custom binary protocol. This is unfortunate, and ideally this would transition to msgpack or cbor because the glue code doesn't need to change, only an additional in/out handler needs to be added. The encoding to JSON is so slow that protobuf may win in certain contexts. A ZeroMQ+msgpack allows more performance in all situations due to streaming output (with cbor supporting more streaming output modes).

> Currently if you want to perform payment processing directly from the wallet with async capabilities, you might need a subset of JSON-RPC calls for fetching balances/sending transfers/other unary calls, a --tx-notify callback script to keep track of incoming/outgoing transactions (which requires the consumer of the wallet APIs to have an HTTP server running), and if you want to batch transactions, also a callback to the daemon or use ZeroMQ (another messaging protocol).

Again, I think your concept of "async capabilities" might be limited, but I'm not entirely sure what ideal communication flow you have in mind. JSON-RPC over TCP can support out-of-order responses and push notifications. There are libraries in other languages that already support this. Its not difficult to have HTTP:"/json_rpc" and another TCP connection use the same backend. It requires almost no work.

From my own testing, this setup is a bit brittle (granted, it may be lack of competence on my part). Its also additionally difficult if you want to run the wallet/daemon and your consumer application on different machines (additional firewall config etc).




> This seems rather silly, given what you (rightly) point out below, namely, JSON deserialization isn't magically going to break tomorrow. I will grant that, esp. in statically typed languages, the auto-generated gRPC serialization and deserialization saves a bit of work.

I wouldn't. Your then stuck with all of this auto-generated code everywhere to interface with. Its just as annoying and less flexible. With JSON for instance, there are several different C++ serializers with different features and modes to map to user code.


> If one wants to avoid the callbacks/ZMQ usage, a polling model needs to be used with the RPC methods, which in my opinion is inferior. Depending on scenarios, this polling might add unnecessary load to a wallet (not informed enough to quantify this).

JSON-RPC over TCP can support this. See node-fast for an example

> I am not familiar with the current process for RPC/ZMQ, but from working on the linked PR, a couple of methods are out of date on the RPC side (strict flag for balance methods / new_account count param). Haven't found the ZMQ documentation, and I wouldn't feel confident writing it since the protocol is entirely new to me.

Then why are you confident in writing documentation for gRPC? Have

**Comment by vdero133** [comment]
I think perhaps I should've introduced gRPC a bit better.

>To my knowledge, the JSON RPC interface should be backwards compatible. So, how does another interface reduce upkeep?
It would not in a net basis, but it would be comparatively lighter (maintenance wise) if compared to the current JSON-RPC interface (just for the sake of comparison). Proof of this is documentation lagging behind implemented features, if using gRPC, interface and documentation changes would be done in the same place.

>Auto-generated bindings merely create the illusion of a seamless upgrade; in reality, if the server changed in some backwards-incompatible way, there's a good chance the client needs more than a simple serialization update. In other words, the ability to one-command "upgrade" the client increases the likelihood of subtle client bugs, as compared to such scenarios forcing a breakage the user must spend some time to address.
Could you give a specific example? I'm not quite sure I follow. In any case, if anything, if comparing to JSON-RPC, having an interface definition file would outline a clear contract for our API. I think these concerns are premature, perhaps there is an upgrade/deprecation process for JSON-RPC I should read?

>For example, if both processes run on the same box, and the private key can easily be accessed, TLS buys you nothing but wasted cycles. 
I don't think this is a fair critique, this would probably be the one use case where TLS is not useful.

I think the selling point of gRPC within our context is not security (while it can amply match JSON-RPC), but rather its ease of use for third parties, maintainability and backwards compatibility. I think however it might improve it incidentally, since most places where things can "go wrong" in client libraries is handled by gRPC/protobufs As it currently stands, I think third parties miss out on many features `wallet2` has that either have not been documented, not implemented in either JSON-RPC, or the current protocols do not/cannot support (to my knowledge).

**Comment by vtnerd** [comment]
> JSON-RPC, or the current protocols do not/cannot support (to my knowledge).

Everything is supported with ZeroMQ or JSON-RPC over TCP (or similar). Its not marketed in the same way (upstream in those projects), but the functionality is still there. gRPC hijacked the async word in a different context.

**Comment by vtnerd** [comment]
> since most places where things can "go wrong" in client libraries is handled by gRPC/protobufs

I mentioned this earlier, but I doubt it. There's lots that can go wrong in clients with asynchronous callbacks. gRPC cannot magically determine how different calls are related and should be interpreted - the client programmer still has to do that. These out-of-band notifications are useful but harder to reason about than in-order "blocking" calls.

**Comment by vdero133** [comment]
> > since most places where things can "go wrong" in client libraries is handled by gRPC/protobufs
> 
> I mentioned this earlier, but I doubt it. There's lots that can go wrong in clients with asynchronous callbacks. gRPC cannot magically determine how different calls are related and should be interpreted - the client programmer still has to do that. These out-of-band notifications are useful but harder to reason about than in-order "blocking" calls.
I think this largely depends on what design the interface will have (ie: how much responsibility is put on each callback). I'm not sure if I misunderstood you, but to note gRPC does guarantee message ordering.

**Comment by vdero133** [comment]
I forgot to mention, my initial post on reddit was shadowbanned as my account was new. I thought about repeating the post but I'm not sure how relevant this is to the wider community. 

>Everything is supported with ZeroMQ or JSON-RPC over TCP (or similar). Its not marketed in the same way (upstream in those projects), but the functionality is still there. gRPC hijacked the async word in a different context.

If possible then, I assume it's not implemented? I think just as important is being able to have a single place where we can define and document the contract our interface(s) will implement.

**Comment by iamamyth** [comment]
> For example, if both processes run on the same box, and the private key can easily be accessed, TLS buys you nothing but wasted cycles.

   > I don't think this is a fair critique, this would probably be the one use case where TLS is not useful.

It is, in the context where it was presented, which referenced various online guides about using the wallet without encryption: Many of those guides are showing how to connect to a wallet-rpc on the testnet, or running on the same box via loopback interface under the same user account.

> I think the selling point of gRPC within our context is not security

Agreed, the "better security" argument seemed forced. I would rather focus on the merits and demerits of gRPC for someone actually trying to use the daemon or wallet software, independent of security considerations, because if that case isn't strong enough, the security question proves moot (if the current RPC or daemon software have security problems, they must be fixed, anyways, so gRPC is beside the point).

> I think third parties miss out on many features wallet2 has that either have not been documented, not implemented in either JSON-RPC, or the current protocols do not/cannot support (to my knowledge).

You're probably right that the documentation is outdated in some places. It would be helpful to update the docs, and maybe even introduce some automation in CI to complain about undocumented fields. But, as @vtnerd mentioned, auto-generated "this field exists" docs aren't hugely useful, one needs clear statements about the meaning a field to wield it properly.

**Comment by vdero133** [comment]
>But, as @vtnerd mentioned, auto-generated "this field exists" docs aren't hugely useful, one needs clear statements about the meaning a field to wield it properly.

With [`protoc-gen-doc`](https://github.com/pseudomuto/protoc-gen-doc) it is possible to add contextual comments to the field. I should have probably done more of them in the draft PR. While it is another plugin to depend on, it would be only needed for CI IMO.

**Comment by iamamyth** [comment]
> With protoc-gen-doc it is possible to add contextual comments to the field

My point is that developer documentation effort would be roughly the same in either case: Without protoc, contributors must list the field and then describe its semantics; with protoc, "list the field" can be omitted, but that's not a massive savings. Linting undocumented fields would probably be easier with protoc, so that could be a win, provided the implementation actually took advantage of this possibility.

**Comment by salty-edamame** [comment]
>I think this was already covered, but this doesn't happen by magic. The backend has to careful deprecate things or it breaks clients that didn't upgrade immediately. And upgrading clients is not be trivial if the RPC interface itself changed dramatically.

With the JSON based RPC, there's already no mechanism to do this. You have to hope that your 3 years out of data client library is compatible with the current version of monero-wallet-rpc. GRPC allows you to set a schema version compatibility guarantee on the server. 

If you add a field or new endpoint in the gRPC server, existing generated clients will continue to work! - just like the current JSON RPC system. 

With gRPC we get the same backwards compatibility as the current JSON RPC, but we also get always-up-to-date client libraries for new fields and methods. No more chasing down the author of a library that was last updated years ago to add some new feature added to the RPC server.

Re-implementing the same thing over and over again in different languages is a Sisyphean task. Let's let the compiler do it for us instead.

**Comment by vtnerd** [comment]
> With the JSON based RPC, there's already no mechanism to do this. You have to hope that your 3 years out of data client library is compatible with the current version of monero-wallet-rpc. GRPC allows you to set a schema version compatibility guarantee on the server.

This does not work by magic. The server has to support multiple schemas, and the clients may have non-trivial updates between schemas. Google marketing makes it appear like you just sprinkle a compiler to get everything to work, but that's not the case if the RPC values changed in a big way (rare but it does happen). This does happen.

**Comment by vtnerd** [comment]
> I think this largely depends on what design the interface will have (ie: how much responsibility is put on each callback). I'm not sure if I misunderstood you, but to note gRPC does guarantee message ordering.

According to a 2016 mailing list post by a developer, ordering is only guaranteed within a single RPC stream. There's no guarantee that if a server sends RPC call (1) before subscription stream (2) that client processes (1) before (2). This is typically what complicates event notification systems that cannot be solved with protobuf code generation magic - async response messages are often initially more difficult for programmers to reason about if their behavior is unfamiliar.

**Comment by vtnerd** [comment]
> If possible then, I assume it's not implemented? I think just as important is being able to have a single place where we can define and document the contract our interface(s) will implement.

I did a deep-dive on auto-generated JSON-Schema or CDDL within our codebase while doing ZeroMQ updating. It should be easier for the HTTP server than the ZeroMQ code. JSON-Schemas can be used to generate markdown files or code generation for several languages (its dependent on JSON parser). This is the easiest for the developers because it would auto-update like protobuf, with the same limitations already discussed. This requires a decent but not massive amount of work to implement.

FWIW, there's a markdown file describing how the ZeroMQ PUSH system works, but could use more info on the JSON fields.

**Comment by vtnerd** [comment]
> My point is that developer documentation effort would be roughly the same in either case: Without protoc, contributors must list the field and then describe its semantics; with protoc, "list the field" can be omitted, but that's not a massive savings. Linting undocumented fields would probably be easier with protoc, so that could be a win, provided the implementation actually took advantage of this possibility.

This is mostly my experience, but client developers seem to like it because it guarantees the server developers can't screw up how the data is sent on the wire. Typically glue code is everywhere regardless, especially for projects that sent raw binary data in many fields.

**Comment by salty-edamame** [comment]
> This does not work by magic. The server has to support multiple schemas

That's not true. You **can** support multiple schema versions, but nobody here is proposing that we do that. I'd rather have a schema version incompatibility failure than a silent incompatibility failure the the current JSON RPC.


>clients may have non-trivial updates between schemas

What do you mean by this? Like I mentioned in my previous reply, the client library doesn't need to be updated for the customer application to continue to work in the case of a rpc-server update if there are only field & method additions.

The only time the client library wouldn't be compatible is if fields are renamed/data-type changed or an endpoint is removed. This is the same as what we have now - except we won't need to get 10+ library maintainers to update their libraries.

**Comment by vtnerd** [comment]
> That's not true. You can support multiple schema versions, but nobody here is proposing that we do that. I'd rather have a schema version incompatibility failure than a silent incompatibility failure the the current JSON RPC.

I was unfortunate that I quoted the reply that particular with that response. This was in response to comments about backwards compatibility:

>>    To my knowledge, the JSON RPC interface should be backwards compatible. So, how does another interface reduce upkeep?
>
> If the client is auto-generated, there's no upkeep required for client library maintainers.

@iamamyth and mysellf are talking about the maintaince on the daemon side, while you are focused on the client side. Solving this issue does not require an entirely new framework, there are existing tools within JSON that can solve this, without maintaining an entirely different system.

-----------------

>>    clients may have non-trivial updates between schemas
>
> What do you mean by this? Like I mentioned in my previous reply, the client library doesn't need to be updated for the customer application to continue to work in the case of a rpc-server update if there are only field & method additions.
>
> The only time the client library wouldn't be compatible is if fields are renamed/data-type changed or an endpoint is removed. This is the same as what we have now - except we won't need to get 10+ library maintainers to update their libraries.

Probably, although I'm not certain if a schema and code generation solves every problem these libraries are attempting. Sometimes the libraries provide higher order concepts from a base set of RPC calls. As an example, selecting random outputs would be a good example, its more private when the process happens client side. This requires two RPC calls into the daemon.

A JSON or CDDL schema would alleviate the same problem you are describing.

**Comment by t-900-a** [comment]
> FWIW, there's a markdown file describing how the ZeroMQ PUSH system works, but could use more info on the JSON fields.

https://github.com/monero-project/monero/blob/2eb56f9ef6562b422ba09f8aaededb451ae60f7d/docs/ZMQ.md

**Comment by moneromooo-monero** [comment]
The author said this can be closed on IRC.
