### ISSUE TITLE
sendto: Network is unreachable

### ISSUE THREAD

**Issue by Samuel20354** [monero-project/monero#7904]
When I ran the command `monerod` in the bin dir after a bit of time it said `sendto: Network is unreachable`. I can't find any solutions online what could be the problem?

**Comment by selsta** [comment]
Do you have any issues apart from this message?

**Comment by Samuel20354** [comment]
wat

**Comment by cirocosta** [comment]
Hey @Samuel20354, without much context is hard to help (e.g., which version? which OS? any other logs? did it ever work? have you tried with a higher log-level number? etc).

"Network is unreachable" (`ENETUNREACH`) arrives when the kernel can't find a route to send a packet to in order to reach that destination ip. 

e.g., if I have no routes and ifaces (other than loopback) at all and try to ping `1.1.1.1`, i'll get back an `ENETUNREACH`

```console
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

$ ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

$ ping 1.1.1.1
ping: connect: Network is unreachable
```

**Comment by Samuel20354** [comment]
Oh hi, I just saw this sorry. So the OS that I'm using is Ubuntu it's a VPS from vultr. This is the first time I have ran this and so it has not worked for me before. I don't know how to get the logs or how to change the log number. and I ran the monerod command by its self. This is what happens when I run `ping 1.1.1.1`:
![image](https://user-images.githubusercontent.com/68336568/131251548-01796705-8b23-4d3a-8080-e2cb63537dd6.png)

Thanks!

**Comment by Samuel20354** [comment]
?

**Comment by selsta** [comment]
If `ping 1.1.1.1` fails on your VPS it's not a monero related issue so I don't think the issue tracker here is the best place to resolve this. I would contact Vultr support.

**Comment by Samuel20354** [comment]
ok
