### ISSUE TITLE
bug: I have a transaction that is not recognised by the wallet that the transaction is spending to

### ISSUE THREAD

**Issue by kklash** [monero-project/monero#7968]
I have a transaction that is not recognized by the wallet that the transaction is spending to.

Here is the transaction id: `47edd623ead491914660a78fbb767dc4686b2c2112d385b0aa8795f231e57a2a`
The wallet was created using generate_from_keys.

I was able to decode the transaction using the view-key and wallet-address on https://melo.tools/explorer/mainnet/.

What do I need to provide so we can debug why the monero-wallet-rpc does not recognize the transaction?

**Comment by selsta** [comment]
Are you using subaddresses?

**Comment by kklash** [comment]
I believe so, yes.

**Comment by kklash** [comment]
Correction, it is not a subaddress

**Comment by selsta** [comment]
Can you restore the wallet in monero-wallet-cli and check if it shows up?

**Comment by kklash** [comment]
I tried restoring using `--generate-from-keys` and `--generate-from-spend-key` and I get different results

49hpY9TsAcyHpBUwZFrs9QXjkfnz2q3bv1GsUiq1zLND7ikpZLBithzdxC4iPkw998dadYPHyY2YB7US9vdV5efpN8EKZ7g - This is the address the funds are actually in. Restoring using this address, plus spend & view keys discovers the UTXO.

49hpY9TsAcyHpBUwZFrs9QXjkfnz2q3bv1GsUiq1zLND7qPrSrm7yXsFUvFJW3AV38byU2JGMoNfj25ecbXK15di2FiEEsp - this is the address shown by monero-wallet-cli when restoring using only the spend key (`--generate-from-spend-key`). Restoring this address shows nothing.

**Comment by selsta** [comment]
What if you restore from seed?

**Comment by kklash** [comment]
I don't have the seed for this wallet, only the address + view + spend keys

**Comment by selsta** [comment]
As far as I know you have to use `--generate-from-keys` in this case.

**Comment by kklash** [comment]
Thanks, i tested and confirmed this is working on the latest version of the monero wallet tools. I believe the bug i experienced was caused by a specific version of `monero-wallet-rpc` and has since been fixed

**Comment by yokoloho** [comment]
Hello, I have this problem: https://github.com/comit-network/xmr-btc-swap/issues/879
Could you please hint me how to open correct wallet after my `monero-wallet-rpc` didn't pick monero from atomic swap?
I have `seed.pem`, `<swap-id>` `<swap-id>.keys`, `swap-tool-blockchain-monitoring-wallet.keys` and `swap-tool-blockchain-monitoring-wallet`.  
When I try `monero-wallet-cli --generate-from-keys monero-data/swap-tool-blockchain-monitoring-wallet` it asks me about standard address, which I can't decode from blockchain because it was atomic swap and I don't know private view key.  
And when I open `<swap-id>` or `swap-tool-blockchain-monitoring-wallet` they are empty.
