### ISSUE TITLE
commission 19.73 xmr SOS

### ISSUE THREAD

**Issue by xmrmfjj2** [monero-project/monero#8298]
391d2a8c6d34267d673f06e631e631ea213180f4df7193a37091d540be92a605 transaction posted 2.5 xmr commission 19.73xmr why such a commission? how to return 19.73 help I use Monero GUI Wallet

**Comment by selsta** [comment]
Did you use simple mode? The problem is that simple mode uses a random remote node and it's possible that malicious remote nodes can increase the fee required.

If you still have the GUI open, can you go to Settings -> Log and enter "status" and post the output?

The GUI will display the fee but it's possible that you overlooked it. The fee goes to the miner of the block.

**Comment by SChernykh** [comment]
This transaction was mined in block [2610570](https://xmrchain.net/block/2610570) which was mined by https://xmr.solopool.org/blocks
Try to contact admin of that mining pool.

**Comment by stefanomarty** [comment]
What about a more evident warning like a pop up when fee is > some average high value, asking the user to double confirm. Something like:
Warning!
Transaction fee asked by node is higher than average.
Are you sure you want to confirm this transaction?

**Comment by proudmuslim-dev** [comment]
I agree with @poiuty

**Comment by Mspy1** [comment]
> xmrmfjj2 lost 19.73 XMR. It is important not only to fix the bug. But also to help return the funds. Possible via funding required https://ccs.getmonero.org

That block was mined by xmr solo pool "https://xmr.solopool.org/blocks", it is possible for them to return it. But highly unlikely.

**Comment by xmrmfjj2** [comment]
thanks wrote to pool waiting for a reply

**Comment by xmrmfjj2** [comment]
help how to return the money

**Comment by HardenedSteel** [comment]
@xmrmfjj2 sorry you can't recover your coins. Please check transaction fees before sending.
