### ISSUE TITLE
Window does not drag consistently when using Custom Decorations (Monero Wallet Gui)

### ISSUE THREAD

**Issue by SkyeG06** [monero-project/monero#8436]
When dragging the window on Linux based systems (Xorg, if that matters) it does not stay bound to the cursor.

**Comment by hyc** [comment]
Wrong repo, should report it there https://github.com/monero-project/monero-gui/

**Comment by selsta** [comment]
Since using custom decorations is kinda a hack with Qt, we had to write our own resize code which isn't performance efficient. There are some solutions to this but it's quite a bug of work (would require custom code for every OS) which isn't high priority currently.

If it bothers you I would recommend to disable custom decorations.
