### ISSUE TITLE
Update to be compatible with Node.js 18 LTS

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#8646]
This issue requests updating monero-project to be compatible with NodeJS 18 LTS so that downstream clients may update to the latest LTS version.

Currently, monero-project is incompatible with NodeJS 17+ LTS due to the way IPv4 and IPv6 addresses are handled. [See related issue](https://github.com/nodejs/node/issues/40702#issuecomment-958143154).

**Comment by jeffro256** [comment]
How is the current Monero C++ code affected by this? The `monero` core repo uses `libunbound` for DNS resolution which (correct me if I'm wrong) is unrelated to whatever Node.js is doing.

**Comment by woodser** [comment]
If I understand correctly from [this comment](https://github.com/nodejs/node/issues/40702#issuecomment-958143154), Node 16's DNS lookup returns IPv4 addresses, which works with localhost in monero-project, but Node 17+'s DNS lookup switches to IPv6, which breaks with localhost since upstream monero-project binds to IPv4 127.0.0.1. In that case, the resolution would be to somehow improve IPv6 support in monero-project.

**Comment by jtgrassie** [comment]
@woodser this is a nodejs issue (a change to the default resolution), not a Monero issue. Monero binds to 127.0.0.1 by default for RPC, but you can always bind to a specific IPv6 address with `--rpc-bind-ipv6-address`. Alternatively, in your nodejs code, use 127.0.0.1 as the host (instead of trying to resolve "localhost") or change your nodejs code to specifically lookup the IPv4 address.

**Comment by jtgrassie** [comment]
@Spederan
> It should be the job of Monero-Project to be compatible with NodeJS

Monero _is already_ compatible with nodejs (and anything else which wants to call it's RPC interface). That's the point. Monero RPC listens on (by default) 127.0.0.1. Regardless of you local setup (which defines what the domain name "localhost" resolves to), and regardless of how anything else (like nodejs) chooses to resolve "localhost". 

nodejs changed its preference to return the IPv6 (if both are defined), but you can still ask for resolution to return the IPv4 address instead. Hence this is absolutely NOT a Monero compatibility issue. Your (and woodser's) complaint is essentially "I want to use 'localhost' in nodejs, instead of '127.0.0.1', but nodejs has started to prefer to return the IPv6 address for localhost, instead of the IPv4 address like it used to. Please fix Monero", which is wrong. Change your code, or change you system config, or change your Monero default config.

**Comment by woodser** [comment]
> Monero is already compatible with nodejs (and anything else which wants to call it's RPC interface). That's the point. Monero RPC listens on (by default) 127.0.0.1. Regardless of you local setup (which defines what the domain name "localhost" resolves to), and regardless of how anything else (like nodejs) chooses to resolve "localhost".

Makes sense to me.

@Spederan You should be able to upgrade to latest Node.js LTS either by using 127.0.0.1 explicitly or by passing the `-no-experimental-fetch` flag to Node.js, in which case this issue can be closed. Basically, monero-project should not assume localhost resolves to 127.0.0.1.

**Comment by Spederan** [comment]
> @Spederan
> 
> > It should be the job of Monero-Project to be compatible with NodeJS
> 
> Monero _is already_ compatible with nodejs (and anything else which wants to call it's RPC interface). That's the point. Monero RPC listens on (by default) 127.0.0.1. Regardless of you local setup (which defines what the domain name "localhost" resolves to), and regardless of how anything else (like nodejs) chooses to resolve "localhost".
> 
> nodejs changed its preference to return the IPv6 (if both are defined), but you can still ask for resolution to return the IPv4 address instead. Hence this is absolutely NOT a Monero compatibility issue. Your (and woodser's) complaint is essentially "I want to use 'localhost' in nodejs, instead of '127.0.0.1', but nodejs has started to prefer to return the IPv6 address for localhost, instead of the IPv4 address like it used to. Please fix Monero", which is wrong. Change your code, or change you system config, or change your Monero default config.

I am literally following the example listed on the github repository. Nowhere am I using localhost. You are making that up.

![monero2](https://user-images.githubusercontent.com/117870702/206281260-d793b0a0-73a7-456f-aa79-962622221313.png)

![monero1](https://user-images.githubusercontent.com/117870702/206281287-b1ae2f50-cc10-44ce-bb4b-099759077d02.png)

**Comment by jtgrassie** [comment]
@Spederan 
> I am literally following the example listed on the github repository....

You're literally relying on the _defaults_, which use localhost. Your issue has nothing to do with _this_ project but rather your lack of understanding how to use another project.

**Comment by woodser** [comment]
@Spederan I can investigate the issue of creating a keys-only wallet with Node 18 separately.

In the meantime, you reported success using the `-no-experimental-fetch` passed to Node.

Either way, closing this issue as unrelated to monero-project itself. If we identify something specific which needs updated, we can open a new issue for that.
