### ISSUE TITLE
Idea: use std::unique_ptr deleter to support custom destructor in custom smart pointer in dns_utils?

### ISSUE THREAD

**Issue by ndcroos** [monero-project/monero#8732]
There is this line with a TODO:
https://github.com/monero-project/monero/blob/9489586add5116a48039616140bb7267b16ba7b1/src/common/dns_utils.cpp#L198

std::unique_ptr supports a custom deleter, but I am not sure if this fits all requirements.

**Comment by 0xFFFC0000** [comment]
The problem is not the deleter. The problem is none of the smart pointer libraries in std (or Boost) provide an easy way to do `&` like we do it [here](https://github.com/monero-project/monero/blob/9489586add5116a48039616140bb7267b16ba7b1/src/common/dns_utils.cpp#L335). 

Of course, it would be possible to get `.get()` the pointer and get the address and use it, but it is not as clean as `&scoped_ptr_variable`.

P.S. `auto_ptr` is deperacated. std provides `unique_ptr` as a replacement.

**Comment by vtnerd** [comment]
I think converting to `.get()` is fine here.

**Comment by vtnerd** [comment]
Nevermind, I see the issue. `operator&` is returning a `**`, which cannot simulate easily. I thought there was something in Boost for this (or at least proposed), but I cannot find it at the moment.
