### ISSUE TITLE
Assistance needed to regain access to my account

### ISSUE THREAD

**Issue by JAAFAR1996** [monero-project/monero#8921]
I recently experienced an issue with my personal computer that unfortunately caused me to lose access to my electronic wallet with your institution.

Specifically, I found it necessary to do a complete reset and reinstall of my computer's operating system and applications. As a result, I seem to have lost access to my wallet/account.

When I attempt to log in using my usual credentials, the balance shows zero despite the fact that I previously had funds in the wallet.

I hope you may be able to assist me in regaining access to my wallet and determining if my previous balance is still intact. Please let me know what additional details or information I can provide to help you investigate and resolve this issue.

I appreciate your understanding and look forward to your reply. Thank you in advance.

**Comment by selsta** [comment]
Which wallet are you using?

**Comment by JAAFAR1996** [comment]
Monero GUI Wallet for Windows 64-bit

**Comment by selsta** [comment]
Can you go to Settings -> Info and share what "Wallet mode" and "Wallet restore height" you have?

**Comment by JAAFAR1996** [comment]
Wallet mode : Simple mode
Wallet restore height: 2838868

**Comment by selsta** [comment]
When was the first time you have received funds into your wallet? Approximately which month / year?

**Comment by selsta** [comment]
And just to confirm the transaction history shows zero transactions? And your wallet address matches your old address?

**Comment by selsta** [comment]
Is the wallet fully synchronized in the bottom left corner?

**Comment by JAAFAR1996** [comment]
yes it is

**Comment by JAAFAR1996** [comment]
But the restore height number is different from what is written in the program now the previous thousand was 2839000 now 2838868

**Comment by plowsof** [comment]
the number being less than what you wrote down is normal (to account for user error i believe the gui will shave a month off the blockheight) 

because you are in simple mode (a remote node randomly selected, which could be 'bad') - i will ask you to 'use another remote node that we know is 'good'. how can we do that? well first we need to change you wallet mode to advanced. 

With your wallet open so you are viewing the balance. click the [<- looking symbol in the top left corner. this will close you wallet. then on this screen you will see a button to "change wallet mode". click this and select advanced. then, you need to click open wallet from file and select this wallet again.

any popup asking you to start a local node - you should cancel. go to settings -> node and make sure that "Remote node" is highlighted by clicking it (the option below Local node)

click on (+) add remote node. in the address field type `selsta2.featherwallet.net` and in the port field type `18081` (username / password not required) click ok. then, click on this node in the list so it is highlighed grey. it should then start connecting.

OK - we're connected but we need to resync from this good node. Go to settings -> info . click change restore height - Do  not adjust the number. simply press ok.. and ok again. then wait until its finished. your true balance should display

**Comment by JAAFAR1996** [comment]
Thank you the full refund has been refunded .. Thank you, friends, for helping me
