### ISSUE TITLE
xmrchain.net api

### ISSUE THREAD

**Issue by kiviw** [monero-project/monero#9016]
xmrchain.net api is down
can someone please fix it
thanks

**Comment by Unkn8wn69** [comment]
I don't think this is the appropriate place for this. If you encounter any issues you can open an issue here:
https://github.com/moneroexamples/onion-monero-blockchain-explorer

Also I think the problem might be on your side because for me everything works fine. I also use the same software for my local block explorer.

**Comment by plowsof** [comment]
@Unkn8wn69 is correct. Alternatives where also shared here https://libera.monerologs.net/monero/20231009#c287864
