### ISSUE TITLE
Why are there 4 numbers in the versioning scheme?

### ISSUE THREAD

**Issue by comminutus** [monero-project/monero#9133]
It seems the first number is always `0`, which suggests that Monero is in some kind of pre-release state.  I doubt this is the case.  Shouldn't the leading `0` be dropped?  If not, does that mean the second and third numbers are minor and patch numbers, and the fourth a build number? 

Perhaps the idea was to follow some kind of similarity with the [Bitcoin version history](https://bitcoin.org/en/version-history)? 🤔

**Comment by Swapnilchavan13** [comment]
Monero's versioning system follows the format MAJOR.MINOR.PATCH, with a leading zero in the major version. The leading zero doesn't imply a pre-release state but is a part of Monero's versioning convention. It is not directly influenced by Bitcoin's versioning scheme. To understand the current versioning details, it's best to check the official Monero documentation or the project's GitHub repository. Versioning conventions may evolve over time in software projects.

**Comment by comminutus** [comment]
> Monero's versioning system follows the format MAJOR.MINOR.PATCH, with a leading zero in the major version. The leading zero doesn't imply a pre-release state but is a part of Monero's versioning convention.

This is evident, the question is why is there a leading "0?"

> To understand the current versioning details, it's best to check the official Monero documentation or the project's GitHub repository. Versioning conventions may evolve over time in software projects.

I did this, hence the reason for the post here. This looks like a ChatGPT response?

**Comment by Fjodor42** [comment]
Hi @comminutus,

The tone of your issue, coupled with your reply to the attempt of an answer to it, prompted me to write the lengthy text below.

I keep it in as an example that the adversarial tone leading up to this might entail further hostilities, but what I actually want to say as a plain answer to you questions is that it is semantic versioning, as defined at https://semver.org/.

The frequent reluctance in F/OSS to commit to a version 1.x.y, as I understand it, often stems from a lack of monetary, organisational and legal ability to commit to a Public API as stipulated in §5 at the link just provided, rendering the notion of pre-release status of 0.x.y versions dependent on the mindset of corporate software.

I hope this clears up the confusion and that we can close this issue.

Best regards,

F

My originally worded answer, sadly:

Well, @comminutus,

If the answer seems compiled from common answers to similar questions, maybe you should prompt yourself to answer why this is important to you, and then use that answer to examine whether your question itself is worth demanding an answer to in the way that you did.

It is not that I don't get your curiosity towards this and, hopefully, many other things in different areas, and, in general, curiosity is to be encouraged as long as it doesn't get pathological.

The thing is, though, that the tone of this issue (and did you notice that you actually went ahead and opened an issue to get an answer?) seems to be the following:

1. I don't like this
2. Because I don't like it, it is wrong
3. Because it is clearly wrong (se3 2.), shouldn't you be doing it this way instead?
4. What does it even mean?
5. Because this is wrong (see 2.), were you just blindly following some other project?

Now, @Swapnilchavan13 actually answered 4., which, to my mind, is the only question that is actually asked in a socially acceptable fashion - at least if you factor out the context in which it was asked, but somehow that was also wrong, according to you.

https://semver.org/, which is where I shall hereby direct you for an answer, might still support you in your understanding that 0.x.y.z is pre-release if you read it wrong, but he deal here is probably more that F/OSS tends to be averse to committing to support a "Public API" (§5 in the link) for times unknown, seeing that most F/OSS projects, at least traditionally, lacked financial backing to commit to such a thing.

As I hope we agree that general discussions on the philosophical ramifications of committing to semantic versioning is outside the scope of this project, I move for this issue to be closed, and discussion  of semantic versioning taken somewhere more appropriate - after having read the specification at the link provided.

Any legitimate concerns as the whether this project employing semantic versioning should not only be predicated on an understanding of the concept, but also a reasonable argument against doing so.

**Comment by comminutus** [comment]
Forgive me if I thought @Swapnilchavan13's response was a generated answer, it seemed like it since the very reason I posted the question was because this information can't be found in the documentation nor the source, otherwise someone would've linked to it by now.

@Fjodor42 I think you're projecting my "tone" and making a lot of assumptions.  I'm not trying to be hostile.  I'm genuinely just curious why there are 4 numbers which make up the version, which are not compatible with SemVer.  Because SemVer is fairly standard these days, most understand an X.Y.Z versioning format to mean major, minor, and release.  Usually, a versioning scheme with 4 numbers adds a "build" component to the set.

Presumably, each component of the version has a meaning, I'm simply after the meaning of each component.  What is the meaning of each component in the Monero versioning scheme?  If the first component (the "0") is arbitrary, why is it so?

**Comment by iamamyth** [comment]
@comminutus See https://github.com/monero-project/meta/issues/721.

**Comment by comminutus** [comment]
@iamamyth that is helpful; I didn't see that (I wasn't looking in the meta repo) - thanks!

Based on that discussion, it seems like the leading 0 in the versioning was to convey the idea that major changes still may come.  While this is understandable, it looks as if the idea was conflated with the ideas of SemVer, making the 2nd component major, 3rd minor, and 4th revision.  This defeats the purpose of the "major" version number change, since major versions typically indicate incompatibility between versions and drastic changes.

Nonetheless, I'll close this because the topic linked by @iamamyth is probably a more relevant place to continue the discussion.
