### ISSUE TITLE
Ask about transactions that see remote nodes

### ISSUE THREAD

**Issue by wipedlifepotato** [monero-project/monero#9471]
Hello. I get information that if enable set_log +daemon.rpc:DEBUG on monerod node, then node can see transaction. Them transactions that see node. Do see node Amount/Who send/Who receive? Or is see only IP + TXs encrypted broadcasting string, that only can be decrypted by Who send/Who receive?

 I tried to found something in source code, but there I found only encrypt for payment_id, and leave this and want to just ask in issue. If someone can show that part in source code I will be happy
 
 If I use local node, then network not see who send transaction?

**Comment by selsta** [comment]
The node you are connected to does not see "Amount/Who send/Who receive", but it does see your IP address.

> If I use local node, then network not see who send transaction?

Since monero is a P2P network, other nodes will see your IP address if your node broadcasts a transaction. To mitigate that, monero uses Dandelion++ https://dl.acm.org/doi/pdf/10.1145/3292040.3219620
